import type { ResourceCatalog } from '../types';

// AWS / SST v4 catalog. Verified against docs/sst-v4-target.md.
export const AWS_CATALOG: ResourceCatalog = {
  nextjs: {
    kind: 'nextjs',
    label: 'Next.js Web',
    defaultName: 'Web',
    component: 'sst.aws.Nextjs',
    description: 'Next.js app on AWS (OpenNext → Lambda/S3/CloudFront)',
    accent: 'bg-neutral-800',
    category: 'compute',
    singleton: true,
    props: [
      { key: 'path', label: 'Path', type: 'text', default: '.', placeholder: '.' },
      { key: 'domain', label: 'Custom domain', type: 'text', placeholder: 'app.example.com' },
      { key: 'environment', label: 'Environment variables', type: 'keyvalue' },
    ],
  },
  bucket: {
    kind: 'bucket',
    label: 'Bucket',
    defaultName: 'Bucket',
    component: 'sst.aws.Bucket',
    description: 'S3 bucket for object storage / uploads',
    accent: 'bg-emerald-600',
    category: 'storage',
    props: [
      {
        key: 'access',
        label: 'Public access',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'Private (default)' },
          { value: 'public', label: 'Public' },
          { value: 'cloudfront', label: 'CloudFront' },
        ],
      },
    ],
  },
  dynamo: {
    kind: 'dynamo',
    label: 'Dynamo',
    defaultName: 'Table',
    component: 'sst.aws.Dynamo',
    description: 'DynamoDB table',
    accent: 'bg-sky-600',
    category: 'database',
    props: [
      { key: 'hashKey', label: 'Partition key', type: 'text', default: 'pk', placeholder: 'pk' },
      {
        key: 'rangeKey',
        label: 'Sort key',
        type: 'text',
        default: 'sk',
        placeholder: 'sk (optional)',
      },
    ],
  },
  queue: {
    kind: 'queue',
    label: 'Queue',
    defaultName: 'Queue',
    component: 'sst.aws.Queue',
    description: 'SQS queue with a Lambda subscriber',
    accent: 'bg-amber-600',
    category: 'messaging',
    props: [{ key: 'fifo', label: 'FIFO queue', type: 'boolean', default: false }],
  },
  worker: {
    kind: 'worker',
    label: 'Worker',
    defaultName: 'Worker',
    component: 'sst.aws.Function',
    description: 'Lambda function (queue subscriber / job handler)',
    accent: 'bg-violet-600',
    category: 'compute',
    props: [
      {
        key: 'timeout',
        label: 'Timeout',
        type: 'text',
        default: '60 seconds',
        placeholder: '60 seconds',
      },
      {
        key: 'memory',
        label: 'Memory',
        type: 'text',
        placeholder: '1024 MB',
        help: 'e.g. "1024 MB"',
      },
    ],
  },
  cron: {
    kind: 'cron',
    label: 'Cron',
    defaultName: 'Cron',
    component: 'sst.aws.CronV2',
    description: 'Scheduled Lambda (CronV2 — not the deprecated Cron)',
    accent: 'bg-rose-600',
    category: 'schedule',
    props: [
      {
        key: 'schedule',
        label: 'Schedule',
        type: 'text',
        default: 'rate(1 day)',
        placeholder: 'rate(1 day) | cron(0 5 * * ? *)',
      },
    ],
  },
  secret: {
    kind: 'secret',
    label: 'Secret',
    defaultName: 'Secret',
    component: 'sst.Secret',
    description: 'Encrypted secret, set via `sst secret set`',
    accent: 'bg-stone-600',
    category: 'config',
  },
  postgres: {
    kind: 'postgres',
    label: 'Postgres',
    defaultName: 'Database',
    component: 'sst.aws.Postgres',
    description: 'RDS Postgres (a VPC is generated automatically)',
    accent: 'bg-cyan-700',
    category: 'database',
  },
  email: {
    kind: 'email',
    label: 'Email',
    defaultName: 'Mailer',
    component: 'sst.aws.Email',
    description: 'Transactional email via Amazon SES',
    accent: 'bg-orange-600',
    category: 'config',
    props: [
      {
        key: 'sender',
        label: 'Sender (email or domain)',
        type: 'text',
        placeholder: 'noreply@example.com',
      },
    ],
  },
  stripe: {
    kind: 'stripe',
    label: 'Stripe',
    defaultName: 'Stripe',
    component: 'Stripe (payments + webhook)',
    description: 'Stripe payments — generates a webhook route + env keys',
    accent: 'bg-indigo-600',
    category: 'config',
  },
  mongodb: {
    kind: 'mongodb',
    label: 'MongoDB',
    defaultName: 'Mongo',
    component: 'MongoDB (Atlas)',
    description: 'External MongoDB via DATABASE_URL (no AWS infra)',
    accent: 'bg-green-700',
    category: 'database',
  },
  externalApi: {
    kind: 'externalApi',
    label: 'External API',
    defaultName: 'ExternalApi',
    component: 'External API (fetch)',
    description: 'Any third-party API — base URL + API key env vars',
    accent: 'bg-teal-600',
    category: 'network',
    props: [
      {
        key: 'baseUrlEnv',
        label: 'Base URL env var',
        type: 'text',
        default: 'API_BASE_URL',
        placeholder: 'API_BASE_URL',
      },
      {
        key: 'keyEnv',
        label: 'API key env var',
        type: 'text',
        default: 'API_KEY',
        placeholder: 'API_KEY',
      },
    ],
  },
  ai: {
    kind: 'ai',
    label: 'AI Chat',
    defaultName: 'AnthropicKey',
    component: 'Anthropic (Claude)',
    description: 'Streaming Claude chat — API key stored as an SST secret',
    accent: 'bg-fuchsia-700',
    category: 'config',
    props: [
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        default: 'claude-opus-4-8',
        options: [
          { value: 'claude-opus-4-8', label: 'Claude Opus 4.8' },
          { value: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6' },
          { value: 'claude-haiku-4-5', label: 'Claude Haiku 4.5' },
        ],
      },
    ],
  },
};

export const AWS_CATALOG_ORDER = [
  'nextjs',
  'bucket',
  'dynamo',
  'postgres',
  'queue',
  'worker',
  'cron',
  'secret',
  'email',
  'stripe',
  'mongodb',
  'externalApi',
  'ai',
];
