import type { ResourceCatalog } from '../types';

// AWS / SST v4 catalog. Verified against docs/sst-v4-target.md.
export const AWS_CATALOG: ResourceCatalog = {
  nextjs: {
    kind: 'nextjs',
    label: 'Next.js Web',
    defaultName: 'Web',
    component: 'sst.aws.Nextjs',
    description: 'Next.js app on AWS (OpenNext → Lambda/S3/CloudFront)',
    accent: 'bg-neutral-800',
    category: 'compute',
    singleton: true,
    props: [
      { key: 'path', label: 'Path', type: 'text', default: '.', placeholder: '.' },
      { key: 'domain', label: 'Custom domain', type: 'text', placeholder: 'app.example.com' },
      { key: 'environment', label: 'Environment variables', type: 'keyvalue' },
    ],
  },
  staticsite: {
    kind: 'staticsite',
    label: 'Static Site',
    defaultName: 'Site',
    component: 'sst.aws.StaticSite',
    description: 'Static / SPA site on its own CloudFront (S3 + CDN)',
    accent: 'bg-slate-700',
    category: 'compute',
    props: [
      { key: 'path', label: 'Path', type: 'text', default: '.', placeholder: 'packages/web' },
      { key: 'buildCommand', label: 'Build command', type: 'text', placeholder: 'npm run build' },
      { key: 'buildOutput', label: 'Build output dir', type: 'text', placeholder: 'dist' },
      {
        key: 'routePath',
        label: 'Router path (when routed)',
        type: 'text',
        placeholder: '/docs',
        help: 'Path pattern when a Router serves this site.',
      },
    ],
  },
  bucket: {
    kind: 'bucket',
    label: 'Bucket',
    defaultName: 'Bucket',
    component: 'sst.aws.Bucket',
    description: 'S3 bucket for object storage / uploads',
    accent: 'bg-emerald-600',
    category: 'storage',
    props: [
      {
        key: 'access',
        label: 'Public access',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'Private (default)' },
          { value: 'public', label: 'Public' },
          { value: 'cloudfront', label: 'CloudFront' },
        ],
      },
      {
        key: 'routePath',
        label: 'Router path (when routed)',
        type: 'text',
        placeholder: '/files',
        help: 'Path pattern when a Router serves this bucket. Requires access: CloudFront.',
      },
    ],
  },
  dynamo: {
    kind: 'dynamo',
    label: 'Dynamo',
    defaultName: 'Table',
    component: 'sst.aws.Dynamo',
    description: 'DynamoDB table',
    accent: 'bg-sky-600',
    category: 'database',
    props: [
      { key: 'hashKey', label: 'Partition key', type: 'text', default: 'pk', placeholder: 'pk' },
      {
        key: 'rangeKey',
        label: 'Sort key',
        type: 'text',
        default: 'sk',
        placeholder: 'sk (optional)',
      },
      {
        key: 'gsiName',
        label: 'GSI name (optional)',
        type: 'text',
        placeholder: 'byStatus',
        help: 'Adds a global secondary index for querying by a non-key attribute.',
      },
      { key: 'gsiHashKey', label: 'GSI partition key', type: 'text', placeholder: 'status' },
      {
        key: 'gsiRangeKey',
        label: 'GSI sort key (optional)',
        type: 'text',
        placeholder: 'createdAt',
      },
    ],
  },
  queue: {
    kind: 'queue',
    label: 'Queue',
    defaultName: 'Queue',
    component: 'sst.aws.Queue',
    description: 'SQS queue with a Lambda subscriber',
    accent: 'bg-amber-600',
    category: 'messaging',
    props: [{ key: 'fifo', label: 'FIFO queue', type: 'boolean', default: false }],
  },
  bus: {
    kind: 'bus',
    label: 'Event Bus',
    defaultName: 'Bus',
    component: 'sst.aws.Bus',
    description: 'EventBridge bus — pub/sub events to Lambda subscribers',
    accent: 'bg-amber-500',
    category: 'messaging',
  },
  snstopic: {
    kind: 'snstopic',
    label: 'SNS Topic',
    defaultName: 'Topic',
    component: 'sst.aws.SnsTopic',
    description: 'SNS topic — fan-out messages to subscribers',
    accent: 'bg-rose-500',
    category: 'messaging',
    props: [{ key: 'fifo', label: 'FIFO topic', type: 'boolean', default: false }],
  },
  apigatewayv2: {
    kind: 'apigatewayv2',
    label: 'HTTP API',
    defaultName: 'Api',
    component: 'sst.aws.ApiGatewayV2',
    description: 'HTTP API Gateway — workers handle routes (METHOD /path)',
    accent: 'bg-sky-600',
    category: 'network',
  },
  router: {
    kind: 'router',
    label: 'Router',
    defaultName: 'Router',
    component: 'sst.aws.Router',
    description: 'CloudFront front-door that routes paths to buckets / static sites',
    accent: 'bg-indigo-500',
    category: 'network',
    props: [{ key: 'domain', label: 'Custom domain', type: 'text', placeholder: 'example.com' }],
  },
  worker: {
    kind: 'worker',
    label: 'Worker',
    defaultName: 'Worker',
    component: 'sst.aws.Function',
    description: 'Lambda function (queue subscriber / job / API route handler)',
    accent: 'bg-violet-600',
    category: 'compute',
    props: [
      {
        key: 'timeout',
        label: 'Timeout',
        type: 'text',
        default: '60 seconds',
        placeholder: '60 seconds',
      },
      {
        key: 'memory',
        label: 'Memory',
        type: 'text',
        placeholder: '1024 MB',
        help: 'e.g. "1024 MB"',
      },
      {
        key: 'route',
        label: 'API route (when wired to an HTTP API)',
        type: 'text',
        default: 'GET /',
        placeholder: 'POST /webhooks/stripe',
      },
    ],
  },
  cron: {
    kind: 'cron',
    label: 'Cron',
    defaultName: 'Cron',
    component: 'sst.aws.CronV2',
    description: 'Scheduled Lambda (CronV2 — not the deprecated Cron)',
    accent: 'bg-rose-600',
    category: 'schedule',
    props: [
      {
        key: 'schedule',
        label: 'Schedule',
        type: 'text',
        default: 'rate(1 day)',
        placeholder: 'rate(1 day) | cron(0 5 * * ? *)',
      },
    ],
  },
  secret: {
    kind: 'secret',
    label: 'Secret',
    defaultName: 'Secret',
    component: 'sst.Secret',
    description: 'Encrypted secret, set via `sst secret set`',
    accent: 'bg-stone-600',
    category: 'config',
  },
  postgres: {
    kind: 'postgres',
    label: 'Postgres',
    defaultName: 'Database',
    component: 'sst.aws.Postgres',
    description: 'RDS Postgres (a VPC is generated automatically)',
    accent: 'bg-cyan-700',
    category: 'database',
    props: [
      {
        key: 'nat',
        label: 'NAT (internet from private subnets)',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None — cheapest, no internet egress' },
          { value: 'ec2', label: 'fck-nat EC2 — ~$4/mo (≈10× cheaper)' },
          { value: 'managed', label: 'Managed NAT Gateway — ~$32/mo/AZ' },
        ],
        help: 'SST VPCs have no NAT by default. Add one only if Lambdas in the VPC must reach the public internet. fck-nat (nat: "ec2") is a cheap t4g.nano NAT instance.',
      },
    ],
  },
  aurora: {
    kind: 'aurora',
    label: 'Aurora',
    defaultName: 'Database',
    component: 'sst.aws.Aurora',
    description: 'Aurora Postgres Serverless v2 (auto-scaling; a VPC is generated)',
    accent: 'bg-cyan-800',
    category: 'database',
    props: [
      {
        key: 'nat',
        label: 'NAT (internet from private subnets)',
        type: 'select',
        default: 'none',
        options: [
          { value: 'none', label: 'None — cheapest, no internet egress' },
          { value: 'ec2', label: 'fck-nat EC2 — ~$4/mo (≈10× cheaper)' },
          { value: 'managed', label: 'Managed NAT Gateway — ~$32/mo/AZ' },
        ],
        help: 'Same VPC/NAT behavior as Postgres — no NAT by default.',
      },
    ],
  },
  email: {
    kind: 'email',
    label: 'Email',
    defaultName: 'Mailer',
    component: 'sst.aws.Email',
    description: 'Transactional email via Amazon SES',
    accent: 'bg-orange-600',
    category: 'config',
    props: [
      {
        key: 'sender',
        label: 'Sender (email or domain)',
        type: 'text',
        placeholder: 'noreply@example.com',
      },
    ],
  },
  stripe: {
    kind: 'stripe',
    label: 'Stripe',
    defaultName: 'Stripe',
    component: 'Stripe (payments + webhook)',
    description: 'Stripe payments — generates a webhook route + env keys',
    accent: 'bg-indigo-600',
    category: 'config',
  },
  mongodb: {
    kind: 'mongodb',
    label: 'MongoDB',
    defaultName: 'Mongo',
    component: 'MongoDB (Atlas)',
    description: 'External MongoDB via DATABASE_URL (no AWS infra)',
    accent: 'bg-green-700',
    category: 'database',
  },
  externalApi: {
    kind: 'externalApi',
    label: 'External API',
    defaultName: 'ExternalApi',
    component: 'External API (fetch)',
    description: 'Any third-party API — base URL + API key env vars',
    accent: 'bg-teal-600',
    category: 'network',
    props: [
      {
        key: 'baseUrlEnv',
        label: 'Base URL env var',
        type: 'text',
        default: 'API_BASE_URL',
        placeholder: 'API_BASE_URL',
      },
      {
        key: 'keyEnv',
        label: 'API key env var',
        type: 'text',
        default: 'API_KEY',
        placeholder: 'API_KEY',
      },
    ],
  },
  cognito: {
    kind: 'cognito',
    label: 'Cognito Auth',
    defaultName: 'AuthPool',
    component: 'sst.aws.CognitoUserPool',
    description: 'AWS Cognito user pool + web client (auth)',
    accent: 'bg-amber-700',
    category: 'config',
  },
  clerk: {
    kind: 'clerk',
    label: 'Clerk Auth',
    defaultName: 'Clerk',
    component: 'Clerk (auth)',
    description: 'Drop-in auth — middleware + env keys (easiest for vibe coders)',
    accent: 'bg-purple-700',
    category: 'config',
  },
  ai: {
    kind: 'ai',
    label: 'AI Chat',
    defaultName: 'AnthropicKey',
    component: 'Anthropic (Claude)',
    description: 'Streaming Claude chat — API key stored as an SST secret',
    accent: 'bg-fuchsia-700',
    category: 'config',
    props: [
      {
        key: 'model',
        label: 'Model',
        type: 'select',
        default: 'claude-opus-4-8',
        options: [
          { value: 'claude-opus-4-8', label: 'Claude Opus 4.8' },
          { value: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6' },
          { value: 'claude-haiku-4-5', label: 'Claude Haiku 4.5' },
        ],
      },
    ],
  },
};

export const AWS_CATALOG_ORDER = [
  'nextjs',
  'staticsite',
  'bucket',
  'dynamo',
  'postgres',
  'aurora',
  'queue',
  'bus',
  'snstopic',
  'apigatewayv2',
  'router',
  'worker',
  'cron',
  'secret',
  'email',
  'cognito',
  'clerk',
  'stripe',
  'mongodb',
  'externalApi',
  'ai',
];
