import type { Blueprint } from '@/lib/core/blueprint/types';
import { collectAwsEnv, type AwsEnvVar } from './env';

// Per-lane export docs (AWS / SST v4). README install/deploy with npm + yarn,
// and a minimal .env.example. See docs/architecture-targets.md (per-lane docs).

function depCommands(pm: 'npm' | 'yarn' | 'pnpm' | 'bun', deps: string[]): string {
  const add =
    pm === 'npm'
      ? 'npm install'
      : pm === 'yarn'
        ? 'yarn add'
        : pm === 'pnpm'
          ? 'pnpm add'
          : 'bun add';
  const run = pm === 'npm' ? 'npx' : pm === 'yarn' ? 'yarn' : pm === 'pnpm' ? 'pnpm' : 'bunx';
  const lines = [`${add} sst`];
  if (deps.length) lines.push(`${add} ${deps.join(' ')}`);
  lines.push(`${run} sst install`);
  lines.push(`${run} sst dev`);
  return lines.join('\n');
}

export function buildAwsReadme(bp: Blueprint, deps: string[]): string {
  const pm = bp.app.packageManager;
  const run = pm === 'npm' ? 'npx' : pm === 'yarn' ? 'yarn' : pm === 'pnpm' ? 'pnpm' : 'bunx';
  const secrets = bp.resources.filter((r) => r.kind === 'secret');

  const secretsSection = secrets.length
    ? `\n## 3. Set secrets\n\n\`\`\`bash\n${secrets
        .map((s) => `${run} sst secret set ${s.name} <value>`)
        .join('\n')}\n\`\`\`\n`
    : '';

  return `# ${bp.app.name}

Generated by **SSTDREAM** — a verified **SST v4** export for **AWS**.
This deploys with SST (OpenNext → Lambda/S3/CloudFront). Nothing here ran on the web;
you run \`sst\` yourself.

## 1. Install SST + dependencies

\`\`\`bash
# ${pm}
${depCommands(pm, deps)}
\`\`\`

<details><summary>npm equivalent</summary>

\`\`\`bash
${depCommands('npm', deps)}
\`\`\`
</details>

## 2. Merge \`package.additions.json\`

Do **not** overwrite your \`package.json\`. Merge the \`dependencies\` and \`scripts\`
from \`package.additions.json\` into your existing \`package.json\`.
${secretsSection}
## ${secrets.length ? '4' : '3'}. Deploy

\`\`\`bash
${run} sst deploy --stage production
\`\`\`

## What's included

- \`sst.config.ts\` — your infrastructure (\`$config\`, \`sst.aws.*\`, links).
- \`lib/\`, \`app/actions/\`, \`src/workers/\` — runtime code that reads linked
  resources via \`import { Resource } from "sst"\`.
- \`package.additions.json\` — dependencies + scripts to merge.
- \`.env.example\` — app environment variables.
- \`sstdream.design.json\` — re-import this into SSTDREAM to keep editing visually.

> SST v4 pins the AWS provider at v7. Re-run \`${run} sst install\` whenever you change providers.
`;
}

export function buildAwsEnvExample(bp: Blueprint): string {
  const vars = collectAwsEnv(bp);
  const groups = new Map<string, AwsEnvVar[]>();
  for (const v of vars) {
    const g = v.group ?? 'App';
    (groups.get(g) ?? groups.set(g, []).get(g)!).push(v);
  }

  const lines: string[] = [
    `# Environment variables for ${bp.app.name} — copy this to .env`,
    `# SST-linked resources (Resource.* from "sst") and SST secrets`,
    `# (sst secret set <Name> <value>) are NOT listed here.`,
    '',
  ];
  for (const [group, gvars] of groups) {
    lines.push(`# ${group}`);
    for (const v of gvars) {
      const value = v.name === 'NEXT_PUBLIC_APP_NAME' ? `"${bp.app.name}"` : '';
      lines.push(`${v.name}=${value}${v.hint ? `          # ${v.hint}` : ''}`);
    }
    lines.push('');
  }
  return `${lines.join('\n')}`;
}
