import type { Blueprint } from '@/lib/core/blueprint/types';
import { collectAwsEnv, type AwsEnvVar } from './env';

// Per-lane export docs (AWS / SST v4). README install/deploy with npm + yarn,
// and a minimal .env.example. See docs/architecture-targets.md (per-lane docs).

function depCommands(pm: 'npm' | 'yarn' | 'pnpm' | 'bun', deps: string[]): string {
  const add =
    pm === 'npm'
      ? 'npm install'
      : pm === 'yarn'
        ? 'yarn add'
        : pm === 'pnpm'
          ? 'pnpm add'
          : 'bun add';
  const run = pm === 'npm' ? 'npx' : pm === 'yarn' ? 'yarn' : pm === 'pnpm' ? 'pnpm' : 'bunx';
  const lines = [`${add} sst`];
  if (deps.length) lines.push(`${add} ${deps.join(' ')}`);
  lines.push(`${run} sst install`);
  lines.push(`${run} sst dev`);
  return lines.join('\n');
}

export function buildAwsReadme(bp: Blueprint, deps: string[]): string {
  const pm = bp.app.packageManager;
  const run = pm === 'npm' ? 'npx' : pm === 'yarn' ? 'yarn' : pm === 'pnpm' ? 'pnpm' : 'bunx';
  const install =
    pm === 'npm'
      ? 'npm install'
      : pm === 'yarn'
        ? 'yarn'
        : pm === 'pnpm'
          ? 'pnpm install'
          : 'bun install';
  const secrets = bp.resources.filter((r) => r.kind === 'secret' || r.kind === 'ai');
  const secretsSection = secrets.length
    ? `\n## 2. Set secrets\n\n\`\`\`bash\n${secrets
        .map((s) => `${run} sst secret set ${s.name} <value>`)
        .join('\n')}\n\`\`\`\n`
    : '';
  const n = secrets.length ? 1 : 0;

  return `# ${bp.app.name}

Generated by **SSTDREAM** — a verified **SST v4** export for **AWS**. This is a **complete,
runnable project** (Next.js 16 + SST → OpenNext → Lambda/S3/CloudFront). Nothing ran on the
web; you run \`sst\` yourself.

## 1. Install

\`\`\`bash
${install}
\`\`\`
${secretsSection}
## ${2 + n}. Run locally

\`\`\`bash
${run} sst dev
\`\`\`

## ${3 + n}. Deploy

\`\`\`bash
${run} sst deploy --stage production
\`\`\`

## What you got

- **\`AGENTS.md\`** — the architecture map: resources, env/secrets, where code lives, and how
  to extend it. **Read this first** (and hand it to Claude to continue the build).
- \`sst.config.ts\` — infrastructure (\`$config\`, \`sst.aws.*\`, links).
- \`package.json\`, \`tsconfig.json\`, \`next.config.ts\`, \`app/layout.tsx\`, \`app/page.tsx\` — a runnable Next.js project.
- \`lib/\`, \`app/actions/\`, \`app/<resource>/\`, \`src/workers/\`, \`app/api/\` — SDK helpers, \`"use server"\`
  actions, example pages, and Lambda handlers. All read linked resources via \`import { Resource } from "sst"\`.
- \`.env.example\` — copy to \`.env\`. \`sstdream.design.json\` — re-import into SSTDREAM to keep editing visually.

<details><summary>Adding this to an <strong>existing</strong> app instead?</summary>

Skip \`package.json\`/\`tsconfig.json\`/\`next.config.ts\`/\`app/layout.tsx\`/\`app/page.tsx\`, and merge
\`package.additions.json\` (deps + scripts) into your own \`package.json\`:

\`\`\`bash
${depCommands(pm, deps)}
\`\`\`
</details>

> SST v4 pins the AWS provider at v7. Re-run \`${run} sst install\` whenever you change providers.
`;
}

export function buildAwsEnvExample(bp: Blueprint): string {
  const vars = collectAwsEnv(bp);
  const groups = new Map<string, AwsEnvVar[]>();
  for (const v of vars) {
    const g = v.group ?? 'App';
    (groups.get(g) ?? groups.set(g, []).get(g)!).push(v);
  }

  const lines: string[] = [
    `# Environment variables for ${bp.app.name} — copy this to .env`,
    `# SST-linked resources (Resource.* from "sst") and SST secrets`,
    `# (sst secret set <Name> <value>) are NOT listed here.`,
    '',
  ];
  for (const [group, gvars] of groups) {
    lines.push(`# ${group}`);
    for (const v of gvars) {
      const value = v.name === 'NEXT_PUBLIC_APP_NAME' ? `"${bp.app.name}"` : '';
      lines.push(`${v.name}=${value}${v.hint ? `          # ${v.hint}` : ''}`);
    }
    lines.push('');
  }
  return `${lines.join('\n')}`;
}
