// Adversarial corpus for the sst.config.ts reverse parser — diverse real-world
// configs a user might paste (varied formatting, comments, quotes, inline resources,
// multi-line links, the modern container/messaging kinds, tricky names, forward refs).
// Generated by a 4-agent stress workflow (2026-06-25), then verified against the parser.
export interface ReverseCase {
  label: string;
  config: string;
  expectKinds: string[];
  expectNames: string[];
  expectEdgesAtLeast: number;
}

export const REVERSE_CORPUS: ReverseCase[] = [
  {
    label: 'single-line-trailing-commas',
    config:
      '/// <reference path="./.sst/platform/config.d.ts" />\nexport default $config({\n  app(input) { return { name: "shop", home: "aws", removal: input?.stage === "production" ? "retain" : "remove", }; },\n  async run() {\n    const orders = new sst.aws.Dynamo("Orders", { fields: { id: "string", }, primaryIndex: { hashKey: "id", }, });\n    const uploads = new sst.aws.Bucket("Uploads",);\n    const site = new sst.aws.Nextjs("Web", { link: [orders, uploads,], });\n    return { url: site.url, };\n  },\n});',
    expectKinds: ['dynamo', 'bucket', 'nextjs'],
    expectNames: ['Orders', 'Uploads', 'Web'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'interleaved-comments-incl-inside-link-array',
    config:
      'export default $config({\n  app(input) {\n    return { name: "events", home: "aws" };\n  },\n  async run() {\n    // event ingest\n    const bus = new sst.aws.Bus("AppBus"); /* central event bus */\n    const sessions = new sst.aws.Dynamo("Sessions", {\n      // single-table design\n      fields: { pk: "string" },\n      primaryIndex: { hashKey: "pk" },\n    });\n    /* the public web tier */\n    const web = new sst.aws.Nextjs("Storefront", {\n      link: [\n        bus,\n        // sessions table holds the cart\n        sessions,\n      ],\n    });\n  },\n});',
    expectKinds: ['bus', 'dynamo', 'nextjs'],
    expectNames: ['AppBus', 'Sessions', 'Storefront'],
    expectEdgesAtLeast: 1,
  },
  {
    label: 'mixed-quotes-name-first-subscribe',
    config:
      "export default $config({\n  app() { return { name: 'pipeline', home: 'aws' }; },\n  async run() {\n    const queue = new sst.aws.Queue(\"Jobs\");\n    const topic = new sst.aws.SnsTopic(`Notifications`);\n    const table = new sst.aws.Dynamo('Records', { fields: { id: 'string' }, primaryIndex: { hashKey: 'id' } });\n    queue.subscribe(\"ProcessJob\", { handler: \"src/process.handler\", link: [table] });\n    topic.subscribe(`FanOut`, { handler: \"src/fanout.handler\" });\n  },\n});",
    expectKinds: ['queue', 'snstopic', 'dynamo', 'worker'],
    expectNames: ['Jobs', 'Notifications', 'Records', 'ProcessJob', 'FanOut'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'export-const-unusual-indentation',
    config:
      '// infra/data.ts — resources are exported so other infra files + functions can link them.\n// SST evaluates this module inside run(); the unusual indentation is just how it was saved.\n            export const db = new sst.aws.Postgres("Primary", {\n                  vpc,\n                        nat: "managed",\n            });\n\n        export const cache = new sst.aws.Redis("Sessions", { engine: "valkey" });\n\n                    export const api = new sst.aws.Nextjs("Api", {\n   link: [db,\n              cache],\n            });',
    expectKinds: ['postgres', 'redis', 'nextjs'],
    expectNames: ['Primary', 'Sessions', 'Api'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'blank-lines-router-staticsite-cron-secret',
    config:
      'export default $config({\n\n  app() {\n\n    return { name: "marketing", home: "aws" };\n\n  },\n\n  async run() {\n\n\n    const stripeKey = new sst.Secret("StripeKey");\n\n\n    const assets = new sst.aws.Bucket("Assets");\n\n\n    const router = new sst.aws.Router("Edge", {\n\n      link: [assets],\n\n    });\n\n\n    const docs = new sst.aws.StaticSite("Docs", {\n\n      path: "packages/docs",\n\n      link: [router],\n\n    });\n\n\n    const reindex = new sst.aws.CronV2("Reindex", {\n\n      schedule: "rate(1 day)",\n\n      link: [stripeKey],\n\n      function: "src/reindex.handler",\n\n    });\n\n  },\n\n});',
    expectKinds: ['secret', 'bucket', 'router', 'staticsite', 'cron'],
    expectNames: ['StripeKey', 'Assets', 'Edge', 'Docs', 'Reindex'],
    expectEdgesAtLeast: 3,
  },
  {
    label: 'nextjs-links-four',
    config:
      'export default $config({\n  app(input) {\n    return { name: "saas", removal: input?.stage === "production" ? "retain" : "remove", home: "aws" };\n  },\n  async run() {\n    const uploads = new sst.aws.Bucket("Uploads", { access: "public" });\n    const db = new sst.aws.Postgres("Db", { vpc, proxy: true });\n    const cache = new sst.aws.Redis("Cache", { engine: "valkey", vpc });\n    const stripeKey = new sst.Secret("StripeSecretKey");\n    const web = new sst.aws.Nextjs("Web", {\n      path: "packages/web",\n      domain: { name: "app.example.com", redirects: ["www.example.com"] },\n      environment: { NEXT_PUBLIC_URL: "https://app.example.com", NODE_OPTIONS: "--max-old-space-size=4096" },\n      link: [uploads, db, cache, stripeKey],\n    });\n    return { url: web.url };\n  },\n});',
    expectKinds: ['nextjs', 'bucket', 'postgres', 'redis', 'secret'],
    expectNames: ['Web', 'Uploads', 'Db', 'Cache', 'StripeSecretKey'],
    expectEdgesAtLeast: 4,
  },
  {
    label: 'inline-bucket-statement',
    config:
      '/// <reference path="./.sst/platform/config.d.ts" />\nexport default $config({\n  app() { return { name: "media", home: "aws" }; },\n  async run() {\n    new sst.aws.Bucket("PublicAssets");\n    const thumbs = new sst.aws.Bucket("Thumbnails");\n    const queue = new sst.aws.Queue("ResizeJobs");\n    queue.subscribe("Resizer", {\n      handler: "src/resize.handler",\n      link: [thumbs],\n      timeout: "5 minutes",\n    });\n  },\n});',
    expectKinds: ['bucket', 'bucket', 'queue', 'worker'],
    expectNames: ['PublicAssets', 'Thumbnails', 'ResizeJobs', 'Resizer'],
    expectEdgesAtLeast: 1,
  },
  {
    label: 'link-array-multiline-order',
    config:
      'export default $config({\n  async run() {\n    const events = new sst.aws.Bus("Events");\n    const orders = new sst.aws.Dynamo("Orders", {\n      fields: { pk: "string", sk: "string" },\n      primaryIndex: { hashKey: "pk", rangeKey: "sk" },\n      stream: "new-and-old-images",\n    });\n    const notify = new sst.aws.Email("Notifications", { sender: "noreply@example.com" });\n    const api = new sst.aws.Nextjs("Storefront", {\n      link: [\n        orders,\n        events,\n        notify,\n      ],\n      transform: {\n        server: { memory: "1024 MB" },\n      },\n    });\n  },\n});',
    expectKinds: ['bus', 'dynamo', 'email', 'nextjs'],
    expectNames: ['Events', 'Orders', 'Notifications', 'Storefront'],
    expectEdgesAtLeast: 3,
  },
  {
    label: 'cron-worker-secret',
    config:
      'export default $config({\n  async run() {\n    const apiKey = new sst.Secret("ApiKey");\n    const reports = new sst.aws.Bucket("Reports");\n    const generator = new sst.aws.Function("ReportGenerator", {\n      handler: "src/reports.handler",\n      link: [reports, apiKey],\n      environment: { TZ: "UTC" },\n    });\n    new sst.aws.CronV2("DailyReport", {\n      schedule: "rate(1 day)",\n      function: generator.arn,\n    });\n  },\n});',
    expectKinds: ['secret', 'bucket', 'worker', 'cron'],
    expectNames: ['ApiKey', 'Reports', 'ReportGenerator', 'DailyReport'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'service-task-containers',
    config:
      'export default $config({\n  app() { return { name: "platform", home: "aws" }; },\n  async run() {\n    const vpc = new sst.aws.Vpc("Vpc", { nat: "ec2" });\n    const cluster = new sst.aws.Cluster("Cluster", { vpc });\n    const db = new sst.aws.Aurora("Database", { engine: "postgres", vpc, nat: "managed" });\n    const api = new sst.aws.Service("Api", {\n      cluster,\n      cpu: "0.5 vCPU",\n      memory: "1 GB",\n      loadBalancer: { rules: [{ listen: "443/https", forward: "3000/http" }] },\n      link: [db],\n    });\n    const migrate = new sst.aws.Task("Migrate", {\n      cluster,\n      cpu: "0.25 vCPU",\n      memory: "0.5 GB",\n      link: [db],\n    });\n  },\n});',
    expectKinds: ['aurora', 'service', 'task'],
    expectNames: ['Database', 'Api', 'Migrate'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'container-data-graph-vpc-cluster-skipped',
    config:
      'export default $config({\n  app(input) {\n    return { name: "shop", removal: input.stage === "production" ? "retain" : "remove", home: "aws" };\n  },\n  async run() {\n    const vpc = new sst.aws.Vpc("Vpc", { nat: "ec2" });\n    const cluster = new sst.aws.Cluster("Cluster", { vpc });\n\n    const db = new sst.aws.Postgres("Db", { vpc, nat: "managed" });\n    const cache = new sst.aws.Redis("Cache", { vpc, engine: "valkey" });\n    const media = new sst.aws.Bucket("Media");\n\n    const api = new sst.aws.Service("Api", {\n      cluster,\n      cpu: "1 vCPU",\n      memory: "2 GB",\n      link: [db, cache, media],\n      loadBalancer: { rules: [{ listen: "80/http", forward: "3000/http" }] },\n    });\n\n    const importer = new sst.aws.Task("Importer", {\n      cluster,\n      cpu: "0.5 vCPU",\n      memory: "1 GB",\n      link: [db, media],\n    });\n\n    return { api: api.url };\n  },\n});',
    expectKinds: ['postgres', 'redis', 'bucket', 'service', 'task'],
    expectNames: ['Db', 'Cache', 'Media', 'Api', 'Importer'],
    expectEdgesAtLeast: 5,
  },
  {
    label: 'public-vs-private-service-loadbalancer-derives-public',
    config:
      'export default $config({\n  app() {\n    return { name: "streams", home: "aws" };\n  },\n  async run() {\n    const vpc = new sst.aws.Vpc("Vpc");\n    const cluster = new sst.aws.Cluster("Cluster", { vpc });\n\n    const orders = new sst.aws.Dynamo("Orders", {\n      fields: { id: "string" },\n      primaryIndex: { hashKey: "id" },\n    });\n    const events = new sst.aws.Bus("Events");\n\n    const gateway = new sst.aws.Service("Gateway", {\n      cluster,\n      cpu: "2 vCPU",\n      memory: "4 GB",\n      link: [orders, events],\n      loadBalancer: {\n        rules: [\n          { listen: "443/https", forward: "8080/http" },\n          { listen: "80/http", forward: "8080/http", redirect: "443/https" },\n        ],\n        domain: "gateway.example.com",\n      },\n    });\n\n    const worker = new sst.aws.Service("Worker", {\n      cluster,\n      cpu: "0.25 vCPU",\n      memory: "0.5 GB",\n      link: [orders],\n    });\n\n    return { gateway: gateway.url };\n  },\n});',
    expectKinds: ['dynamo', 'bus', 'service'],
    expectNames: ['Orders', 'Events', 'Gateway', 'Worker'],
    expectEdgesAtLeast: 3,
  },
  {
    label: 'realtime-with-authorizer-and-app-link',
    config:
      'export default $config({\n  app() {\n    return { name: "live", home: "aws" };\n  },\n  async run() {\n    const presence = new sst.aws.Bucket("Presence");\n\n    const realtime = new sst.aws.Realtime("Live", {\n      authorizer: "src/realtime-authorizer.handler",\n    });\n\n    realtime.subscribe("src/on-message.handler", {\n      filter: "chat/+/messages",\n    });\n\n    const web = new sst.aws.Nextjs("Web", {\n      link: [realtime, presence],\n    });\n\n    return { web: web.url };\n  },\n});',
    expectKinds: ['bucket', 'realtime', 'nextjs'],
    expectNames: ['Presence', 'Live', 'Web'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'stepfunctions-static-builders-started-by-app',
    config:
      'export default $config({\n  app() {\n    return { name: "pipeline", home: "aws" };\n  },\n  async run() {\n    const docs = new sst.aws.Bucket("Docs");\n\n    const validate = sst.aws.StepFunctions.lambdaInvoke({\n      name: "Validate",\n      function: "src/steps/validate.handler",\n    });\n    const process = sst.aws.StepFunctions.lambdaInvoke({\n      name: "Process",\n      function: "src/steps/process.handler",\n    });\n    const done = sst.aws.StepFunctions.succeed({ name: "Done" });\n\n    const pipeline = new sst.aws.StepFunctions("Pipeline", {\n      definition: validate.next(process).next(done),\n      type: "standard",\n    });\n\n    const web = new sst.aws.Nextjs("Web", {\n      link: [pipeline, docs],\n    });\n\n    return { web: web.url };\n  },\n});',
    expectKinds: ['bucket', 'stepFunctions', 'nextjs'],
    expectNames: ['Docs', 'Pipeline', 'Web'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'queue-worker-subscriber-plus-app-publishes',
    config:
      'export default $config({\n  app() {\n    return { name: "jobs", home: "aws" };\n  },\n  async run() {\n    const dlq = new sst.aws.Queue("Dlq");\n    const jobs = new sst.aws.Queue("Jobs", {\n      dlq: dlq.arn,\n    });\n    const results = new sst.aws.Dynamo("Results", {\n      fields: { id: "string" },\n      primaryIndex: { hashKey: "id" },\n    });\n\n    jobs.subscribe("JobProcessor", {\n      handler: "src/processor.handler",\n      link: [results],\n    });\n\n    const web = new sst.aws.Nextjs("Web", {\n      link: [jobs],\n    });\n\n    return { web: web.url };\n  },\n});',
    expectKinds: ['queue', 'dynamo', 'nextjs', 'worker'],
    expectNames: ['Dlq', 'Jobs', 'Results', 'Web', 'JobProcessor'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'tricky-names-forward-ref',
    config:
      '/// <reference path="./.sst/platform/config.d.ts" />\nexport default $config({\n  app(input) {\n    return { name: "my-app", home: "aws" };\n  },\n  async run() {\n    const web = new sst.aws.Nextjs("Marketing Site", {\n      link: [media, sessions],\n    });\n    const media = new sst.aws.Bucket("user-uploads-bucket");\n    const sessions = new sst.aws.Dynamo("Café-Sessions™", {\n      fields: { pk: "string" },\n      primaryIndex: { hashKey: "pk" },\n    });\n  },\n});',
    expectKinds: ['nextjs', 'bucket', 'dynamo'],
    expectNames: ['Marketing Site', 'user-uploads-bucket', 'Café-Sessions™'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'namefirst-subscribe-vs-handlerpath',
    config:
      'export default $config({\n  app() { return { name: "events", home: "aws" }; },\n  async run() {\n    const queue = new sst.aws.Queue("IngestQueue");\n    queue.subscribe("Processor", { timeout: "60 seconds" });\n\n    const realtime = new sst.aws.Realtime("LiveChat", {\n      authorizer: "src/realtime/authorizer.handler",\n    });\n    realtime.subscribe("src/realtime/subscriber.handler", {\n      filter: "chat/+",\n    });\n  },\n});',
    expectKinds: ['queue', 'realtime', 'worker'],
    expectNames: ['IngestQueue', 'LiveChat', 'Processor'],
    expectEdgesAtLeast: 1,
  },
  {
    label: 'multi-subscriber-one-queue',
    config:
      'export default $config({\n  app() { return { name: "pipeline", home: "aws" }; },\n  async run() {\n    const jobs = new sst.aws.Queue("JobsQueue", {\n      visibilityTimeout: "300 seconds",\n    });\n    jobs.subscribe("ThumbnailWorker", { timeout: "120 seconds" });\n    jobs.subscribe("TranscodeWorker", { memory: "2048 MB" });\n    jobs.subscribe("NotifyWorker", {});\n  },\n});',
    expectKinds: ['queue', 'worker', 'worker', 'worker'],
    expectNames: ['JobsQueue', 'ThumbnailWorker', 'TranscodeWorker', 'NotifyWorker'],
    expectEdgesAtLeast: 3,
  },
  {
    label: 'secrets-plus-ai-key',
    config:
      'export default $config({\n  app() { return { name: "chatbot", home: "aws" }; },\n  async run() {\n    const anthropic = new sst.Secret("AnthropicKey");\n    const stripeKey = new sst.Secret("StripeSecretKey");\n    const app = new sst.aws.Nextjs("AI Chatbot", {\n      link: [anthropic, stripeKey],\n    });\n  },\n});',
    expectKinds: ['secret', 'secret', 'nextjs'],
    expectNames: ['AnthropicKey', 'StripeSecretKey', 'AI Chatbot'],
    expectEdgesAtLeast: 2,
  },
  {
    label: 'full-app-skip-vpc-cluster',
    config:
      'export default $config({\n  app() { return { name: "saas", home: "aws" }; },\n  async run() {\n    const vpc = new sst.aws.Vpc("MainVpc", { nat: "ec2" });\n    const cluster = new sst.aws.Cluster("AppCluster", { vpc });\n\n    const db = new sst.aws.Postgres("AppDb", { vpc, nat: "ec2" });\n    const assets = new sst.aws.Bucket("StaticAssets");\n\n    const api = new sst.aws.Service("ApiService", {\n      cluster,\n      cpu: "0.5 vCPU",\n      memory: "1 GB",\n      loadBalancer: { ports: [{ listen: "443/https", forward: "3000/http" }] },\n      link: [db, assets],\n    });\n\n    const reaper = new sst.aws.Function("CleanupFn", {\n      handler: "src/cron/cleanup.handler",\n      link: [db],\n    });\n    const daily = new sst.aws.CronV2("DailyCleanup", {\n      schedule: "rate(1 day)",\n      function: reaper.arn,\n    });\n  },\n});',
    expectKinds: ['postgres', 'bucket', 'service', 'worker', 'cron'],
    expectNames: ['AppDb', 'StaticAssets', 'ApiService', 'CleanupFn', 'DailyCleanup'],
    expectEdgesAtLeast: 3,
  },
];
