import type { ResourceCatalog } from '../types';

// Vercel lane catalog. Verified against docs/vercel-target.md: Blob + Edge Config are
// first-party; KV/Postgres are external Marketplace (Upstash/Neon); Queues + Workflows
// are native. The app hosts on Vercel and integrates services — no app-owned AWS infra.
export const VERCEL_CATALOG: ResourceCatalog = {
  app: {
    kind: 'app',
    label: 'Vercel App',
    defaultName: 'Web',
    component: 'Vercel Next.js Project',
    description: 'Next.js on Vercel (zero-config deploy)',
    accent: 'bg-neutral-800',
    category: 'compute',
    singleton: true,
  },
  blob: {
    kind: 'blob',
    label: 'Blob',
    defaultName: 'Files',
    component: '@vercel/blob',
    description: 'Vercel Blob object storage (first-party)',
    accent: 'bg-emerald-600',
    category: 'storage',
    props: [
      {
        key: 'access',
        label: 'Access',
        type: 'select',
        default: 'public',
        options: [
          { value: 'public', label: 'Public (CDN URLs)' },
          { value: 'private', label: 'Private (signed access)' },
        ],
        help: 'Blob stores have an immutable public|private mode; every method needs a matching access value.',
      },
    ],
  },
  postgres: {
    kind: 'postgres',
    label: 'Postgres',
    defaultName: 'Db',
    component: 'Neon Postgres',
    description: 'External Postgres (Neon / Supabase) via Marketplace',
    accent: 'bg-sky-600',
    category: 'database',
  },
  redis: {
    kind: 'redis',
    label: 'Redis',
    defaultName: 'Cache',
    component: 'Upstash Redis',
    description: 'External Redis (Upstash) via Marketplace',
    accent: 'bg-rose-600',
    category: 'database',
  },
  queue: {
    kind: 'queue',
    label: 'Queue',
    defaultName: 'Jobs',
    component: '@vercel/queue',
    description: 'Vercel Queue (native, beta)',
    accent: 'bg-amber-600',
    category: 'messaging',
  },
  consumer: {
    kind: 'consumer',
    label: 'Consumer',
    defaultName: 'Worker',
    component: 'handleCallback',
    description: 'Queue consumer (push-mode worker)',
    accent: 'bg-violet-600',
    category: 'compute',
    props: [
      {
        key: 'maxDuration',
        label: 'Max duration (seconds)',
        type: 'number',
        placeholder: '300',
        help: 'Function timeout. Default 300s; Pro/Enterprise up to ~800s. Set in vercel.json.',
      },
    ],
  },
  cron: {
    kind: 'cron',
    label: 'Cron',
    defaultName: 'Daily',
    component: 'vercel.json crons',
    description: 'Scheduled API route (production only)',
    accent: 'bg-fuchsia-600',
    category: 'schedule',
    props: [
      {
        key: 'schedule',
        label: 'Schedule (cron)',
        type: 'text',
        default: '0 5 * * *',
        placeholder: '0 5 * * *',
        help: '5-field cron, UTC, numeric only (no MON/JAN). Hobby plan: once/day max.',
      },
    ],
  },
  webhook: {
    kind: 'webhook',
    label: 'Webhook',
    defaultName: 'Webhook',
    component: 'API route',
    description: 'Inbound webhook (Stripe or generic HMAC)',
    accent: 'bg-orange-600',
    category: 'network',
    props: [
      {
        key: 'provider',
        label: 'Provider',
        type: 'select',
        default: 'stripe',
        options: [
          { value: 'stripe', label: 'Stripe' },
          { value: 'generic', label: 'Generic (HMAC signature)' },
        ],
        help: 'Stripe emits Stripe signature verification; Generic emits an HMAC check with a per-hook secret.',
      },
    ],
  },
  email: {
    kind: 'email',
    label: 'Email',
    defaultName: 'Mailer',
    component: 'Resend',
    description: 'Transactional email (Resend)',
    accent: 'bg-pink-600',
    category: 'config',
    props: [
      {
        key: 'from',
        label: 'From address',
        type: 'text',
        default: 'noreply@example.com',
        placeholder: 'noreply@yourdomain.com',
        help: 'Verified sender for Resend. Must be on a domain you verified.',
      },
    ],
  },
  edgeConfig: {
    kind: 'edgeConfig',
    label: 'Edge Config',
    defaultName: 'Config',
    component: '@vercel/edge-config',
    description: 'Low-latency global config store (first-party, read-optimized)',
    accent: 'bg-cyan-600',
    category: 'config',
  },
  externalApi: {
    kind: 'externalApi',
    label: 'External API',
    defaultName: 'Api',
    component: 'fetch helper',
    description: 'A third-party HTTP API the app calls (base URL + key via env)',
    accent: 'bg-teal-600',
    category: 'network',
    props: [
      {
        key: 'baseUrlEnv',
        label: 'Base URL env var',
        type: 'text',
        placeholder: 'WEATHER_BASE_URL',
        help: 'Name of the env var holding the API base URL.',
      },
      {
        key: 'keyEnv',
        label: 'API key env var',
        type: 'text',
        placeholder: 'WEATHER_API_KEY',
        help: 'Name of the env var holding the API key (server-only).',
      },
    ],
  },
  analytics: {
    kind: 'analytics',
    label: 'Analytics',
    defaultName: 'Analytics',
    component: '@vercel/analytics',
    description: 'Vercel Web Analytics — privacy-friendly page/event metrics',
    accent: 'bg-blue-600',
    category: 'config',
    singleton: true,
  },
  speedInsights: {
    kind: 'speedInsights',
    label: 'Speed Insights',
    defaultName: 'SpeedInsights',
    component: '@vercel/speed-insights',
    description: 'Vercel Speed Insights — real-user Core Web Vitals',
    accent: 'bg-violet-600',
    category: 'config',
    singleton: true,
  },
};

export const VERCEL_CATALOG_ORDER = [
  'app',
  'blob',
  'edgeConfig',
  'postgres',
  'redis',
  'queue',
  'consumer',
  'cron',
  'webhook',
  'externalApi',
  'email',
  'analytics',
  'speedInsights',
];
