import type { Blueprint } from '@/lib/core/blueprint/types';
import { collectEnv } from './env';

function pmAdd(pm: 'npm' | 'yarn' | 'pnpm' | 'bun'): string {
  return pm === 'npm'
    ? 'npm install'
    : pm === 'yarn'
      ? 'yarn add'
      : pm === 'pnpm'
        ? 'pnpm add'
        : 'bun add';
}

export function buildVercelReadme(bp: Blueprint, deps: string[]): string {
  const has = (kind: string) => bp.resources.some((r) => r.kind === kind);
  const installs: string[] = [];
  if (has('postgres')) installs.push('vercel install neon      # external Postgres');
  if (has('redis')) installs.push('vercel install upstash   # external Redis');
  const provisionSection = installs.length
    ? `\n## 2. Provision Marketplace services\n\n\`\`\`bash\n${installs.join('\n')}\n\`\`\`\n`
    : '';

  return `# ${bp.app.name}

Generated by **SSTDREAM** — a **Vercel** export. This app deploys **natively on Vercel**
(no SST, no AWS infra). You run \`vercel\` yourself.

## 1. Install dependencies

\`\`\`bash
${deps.length ? `${pmAdd(bp.app.packageManager)} ${deps.join(' ')}` : '# (no extra dependencies)'}
\`\`\`
${provisionSection}
## ${installs.length ? '3' : '2'}. Set environment variables

See \`required-env.json\` and \`.env.example\`. Add them in the Vercel dashboard
(Project → Settings → Environment Variables), then pull locally:

\`\`\`bash
vercel env pull
\`\`\`

## ${installs.length ? '4' : '3'}. Deploy

\`\`\`bash
vercel --prod
\`\`\`

## What's included

- \`vercel.json\` — cron schedules + queue consumer triggers (only if needed).
- \`app/api/...\` — cron / queue-consumer / webhook routes.
- \`lib/...\` — service helpers (Blob, Postgres, Redis, Queue, Email).
- \`required-env.json\` + \`.env.example\` — the variables to configure.
- \`sstdream.design.json\` — re-import into SSTDREAM to keep editing visually.

> Storage note: \`@vercel/kv\`/\`@vercel/postgres\` are retired — this export uses
> **Upstash Redis** and **Neon Postgres** via the Vercel Marketplace.
`;
}

export function buildVercelEnvExample(bp: Blueprint): string {
  const env = collectEnv(bp);
  return `# Environment variables for ${bp.app.name}.
# Set these in Vercel (Project → Settings → Environment Variables) and pull with \`vercel env pull\`.
# NEXT_PUBLIC_ vars are exposed to the browser — never put secrets there.

${env.map((e) => `${e.name}=`).join('\n')}
`;
}
