import type { Blueprint } from '@/lib/core/blueprint/types';
import type { GeneratedFile } from '@/lib/core/codegen/types';
import { kebabCase } from '@/lib/core/codegen/strings';
import { VERCEL_CATALOG } from './catalog';
import { VERCEL_EDGE_INTENTS } from './edges';
import { collectEnv } from './env';

// "New project" scaffold for the Vercel lane: turns the generated integration
// files into a complete, runnable Next.js app you deploy on Vercel. Verified
// against docs/vercel-target.md §0-§1: deploying Next.js to Vercel is zero-config
// (no vercel.json needed for a standard app), Git integration is the recommended
// path, and there is no SST/AWS infra. Mirrors the AWS scaffold so both lanes
// export a real project + an AGENTS.md, not loose fragments.

const sortObj = (o: Record<string, string>): Record<string, string> =>
  Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));

function packageJson(bp: Blueprint, deps: Record<string, string>): string {
  // Verified major ranges (npm registry); service deps come from the generator.
  const dependencies = sortObj({
    next: '^16.0.0',
    react: '^19.0.0',
    'react-dom': '^19.0.0',
    ...deps,
  });
  const pkg = {
    name: kebabCase(bp.app.name) || 'vercel-app',
    version: '0.1.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      // Git integration is the recommended path; this is the manual CLI deploy.
      deploy: 'vercel --prod',
    },
    dependencies,
    devDependencies: sortObj({
      '@types/node': '^25.0.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      typescript: '^6.0.0',
    }),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

const tsconfigJson = (): string =>
  `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
      exclude: ['node_modules'],
    },
    null,
    2,
  )}\n`;

const nextConfig = (): string =>
  `import type { NextConfig } from "next";

// Deploying Next.js to Vercel is zero-config — no special settings needed.
const nextConfig: NextConfig = {};

export default nextConfig;
`;

const gitignore = (): string =>
  `node_modules/
.next/
out/
build/
*.tsbuildinfo
next-env.d.ts
.vercel
.env*.local
.DS_Store
`;

function layoutFile(bp: Blueprint): string {
  return `import type { ReactNode } from "react";

export const metadata = { title: "${bp.app.name}", description: "Generated by SSTDREAM" };

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function pageFile(bp: Blueprint, routes: string[]): string {
  const items = routes.map((r) => `        <li><code>${r}</code></li>`);
  const list = items.length
    ? `      <p>Wired endpoints:</p>
      <ul>
${items.join('\n')}
      </ul>`
    : `      <p>Add resources in SSTDREAM and re-export to scaffold endpoints here.</p>`;
  return `export default function Home() {
  return (
    <main style={{ maxWidth: 720, margin: "3rem auto", fontFamily: "system-ui", lineHeight: 1.6 }}>
      <h1>${bp.app.name}</h1>
      <p>Generated by SSTDREAM — a Next.js app that deploys natively on Vercel.</p>
${list}
      <p style={{ marginTop: 24, color: "#666" }}>
        See <code>AGENTS.md</code> for the architecture and how to extend it.
      </p>
    </main>
  );
}
`;
}

function agentsMd(bp: Blueprint, files: GeneratedFile[]): string {
  const paths = files.map((f) => f.path);
  const has = (re: RegExp) => paths.some((p) => re.test(p));
  const list = (re: RegExp) => paths.filter((p) => re.test(p)).sort();

  const resources = bp.resources
    .map((r) => {
      const meta = VERCEL_CATALOG[r.kind];
      return `- **${r.name}** (${meta?.label ?? r.kind} — \`${meta?.component ?? r.kind}\`)`;
    })
    .join('\n');

  const intentMeta = new Map(VERCEL_EDGE_INTENTS.map((i) => [i.intent, i]));
  const byId = new Map(bp.resources.map((r) => [r.id, r]));
  const dataFlow = bp.connections
    .map((c) => {
      const src = byId.get(c.source);
      const tgt = byId.get(c.target);
      if (!src || !tgt) return null;
      const meta = intentMeta.get(c.intent);
      const label = meta?.label ?? c.intent;
      const why = meta?.description ? ` — ${meta.description}` : '';
      return `- **${src.name}** ${label} **${tgt.name}** (\`${c.intent}\`)${why}`;
    })
    .filter((line): line is string => Boolean(line))
    .join('\n');

  const envVars = collectEnv(bp).filter((v) => v.name !== 'NEXT_PUBLIC_APP_NAME');
  const envLines = envVars.length
    ? envVars.map((v) => `  - \`${v.name}\` (${v.scope})`).join('\n')
    : '  - (only NEXT_PUBLIC_APP_NAME)';

  const sections: string[] = [];
  if (has(/^app\/actions\//))
    sections.push(`- \`app/actions/*\` — \`"use server"\` actions (e.g. uploads).`);
  if (has(/^app\/api\/cron\//))
    sections.push(`- \`app/api/cron/*/route.ts\` — scheduled GET routes (verify \`CRON_SECRET\`).`);
  if (has(/^app\/api\/queues\//))
    sections.push(
      `- \`app/api/queues/*/route.ts\` — push-mode queue consumers (\`handleCallback\`).`,
    );
  if (has(/^app\/api\/webhooks\//))
    sections.push(
      `- \`app/api/webhooks/*/route.ts\` — inbound webhook routes (verify signatures).`,
    );
  if (has(/^lib\//))
    sections.push(`- \`lib/*\` — service helpers (Blob, DB, Redis, Queue, Email).`);

  return `# ${bp.app.name} — Architecture

> Generated by **SSTDREAM**. This is a **Next.js** app that deploys **natively on Vercel**
> (no SST, no AWS infra). Databases/Redis are external managed services the app connects to.
> **Read this before extending the app.**

## Resources

${resources}

## Data flow (the design graph)

${dataFlow || '- (no connections — resources are standalone)'}

> The full machine-readable design is \`sstdream.design.json\` (nodes, edges, intents,
> props). Parse it before structural changes; keep it in sync by re-importing into
> SSTDREAM and re-exporting.

## Deploy

- **Git integration (recommended, zero-config):** push this repo to GitHub/GitLab, import it
  at vercel.com, and every push to your production branch deploys. No \`vercel.json\` needed
  for a standard app.
- **CLI:** \`vercel\` (preview) / \`vercel --prod\` (production).

## Environment

Set these in Vercel (Project → Settings → Environment Variables), then \`vercel env pull\`:

${envLines}

> Server-only keys (\`*_SECRET\`, \`DATABASE_URL\`, API keys) must NEVER be prefixed with
> \`NEXT_PUBLIC_\` — that inlines them into the browser bundle.

## Where things live

${sections.join('\n') || '- A standard Next.js app — add routes under `app/`.'}

## Files of interest

${
  list(/^(lib|app\/actions|app\/api)\//)
    .map((p) => `- \`${p}\``)
    .join('\n') || '- (none yet)'
}

## Hard rules (do not break)

- Storage: use **Upstash Redis** (\`@upstash/redis\`) and **Neon Postgres**
  (\`@neondatabase/serverless\`) — never \`@vercel/kv\` or \`@vercel/postgres\` (both retired).
- \`vercel.json\` is only for overrides (crons, queue triggers, function config) — a standard
  app needs none.
- Re-import \`sstdream.design.json\` into SSTDREAM to keep editing this visually.
`;
}

export function generateVercelScaffold(
  bp: Blueprint,
  files: GeneratedFile[],
  deps: Record<string, string>,
): GeneratedFile[] {
  // Surface the concrete endpoints the design produced on the landing page.
  const routes = files
    .map((f) => {
      const cron = /^app\/api\/cron\/([^/]+)\/route\.ts$/.exec(f.path);
      if (cron) return `GET /api/cron/${cron[1]}`;
      const queue = /^app\/api\/queues\/([^/]+)\/route\.ts$/.exec(f.path);
      if (queue) return `POST /api/queues/${queue[1]} (consumer)`;
      const hook = /^app\/api\/webhooks\/([^/]+)\/route\.ts$/.exec(f.path);
      if (hook) return `POST /api/webhooks/${hook[1]}`;
      return null;
    })
    .filter((s): s is string => Boolean(s));

  return [
    { path: 'package.json', content: packageJson(bp, deps), language: 'json' },
    { path: 'tsconfig.json', content: tsconfigJson(), language: 'json' },
    { path: 'next.config.ts', content: nextConfig(), language: 'ts' },
    { path: '.gitignore', content: gitignore(), language: 'text' },
    { path: 'app/layout.tsx', content: layoutFile(bp), language: 'tsx' },
    { path: 'app/page.tsx', content: pageFile(bp, routes), language: 'tsx' },
    { path: 'AGENTS.md', content: agentsMd(bp, files), language: 'md' },
  ];
}
