import type { Blueprint } from '@/lib/core/blueprint/types';
import type { GeneratedFile } from '@/lib/core/codegen/types';
import { kebabCase } from '@/lib/core/codegen/strings';
import { AWS_CATALOG } from '../catalog';
import { AWS_EDGE_INTENTS } from '../edges';
import { collectAwsEnv } from '../env';

// "New project" scaffold: turns the generated infra/runtime files into a complete,
// runnable Next.js 16 + SST v4 app (yarn install && sst dev) plus an AGENTS.md so
// Claude / any dev can open the export and finish it.

const sortObj = (o: Record<string, string>): Record<string, string> =>
  Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));

function packageJson(
  bp: Blueprint,
  deps: Record<string, string>,
  devDeps: Record<string, string>,
): string {
  // Verified major ranges (npm registry, 2026-06-10).
  const dependencies = sortObj({
    next: '^16.0.0',
    react: '^19.0.0',
    'react-dom': '^19.0.0',
    ...deps,
  });
  const pkg = {
    name: kebabCase(bp.app.name) || 'sst-app',
    version: '0.1.0',
    private: true,
    type: 'module',
    // No lint script: the scaffold ships no eslint config/dependency.
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      'sst:dev': 'sst dev',
      deploy: 'sst deploy',
      remove: 'sst remove',
    },
    dependencies,
    devDependencies: sortObj({
      '@types/node': '^25.0.0',
      '@types/react': '^19.0.0',
      '@types/react-dom': '^19.0.0',
      typescript: '^6.0.0',
      ...devDeps,
    }),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

const tsconfigJson = (): string =>
  `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts', 'sst-env.d.ts'],
      exclude: ['node_modules'],
    },
    null,
    2,
  )}\n`;

const nextConfig = (): string =>
  `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;

const gitignore = (): string =>
  `node_modules/
.next/
.sst/
.open-next/
out/
build/
*.tsbuildinfo
next-env.d.ts
sst-env.d.ts
.env*.local
.DS_Store
`;

function layoutFile(bp: Blueprint): string {
  const clerk = bp.resources.some((r) => r.kind === 'clerk');
  const meta = `export const metadata = { title: "${bp.app.name}", description: "Generated by SSTDREAM" };`;
  if (clerk) {
    return `import type { ReactNode } from "react";
import { ClerkProvider } from "@clerk/nextjs";

${meta}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
`;
  }
  return `import type { ReactNode } from "react";

${meta}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function pageFile(bp: Blueprint, pageRoutes: string[], hasChat: boolean): string {
  const items = [
    ...pageRoutes.map((seg) => `        <li><a href="/${seg}">/${seg}</a> — list + create</li>`),
    ...(hasChat
      ? ['        <li><code>POST /api/chat</code> — streaming Claude endpoint</li>']
      : []),
  ];
  const list = items.length
    ? `      <p>Wired to your resources:</p>
      <ul>
${items.join('\n')}
      </ul>`
    : `      <p>Add resources in SSTDREAM and re-export to scaffold pages here.</p>`;
  return `export default function Home() {
  return (
    <main style={{ maxWidth: 720, margin: "3rem auto", fontFamily: "system-ui", lineHeight: 1.6 }}>
      <h1>${bp.app.name}</h1>
      <p>Generated by SSTDREAM — a verified SST v4 app for AWS.</p>
${list}
      <p style={{ marginTop: 24, color: "#666" }}>
        See <code>AGENTS.md</code> for the architecture and how to extend it.
      </p>
    </main>
  );
}
`;
}

// CI deploy workflow — simple access-key auth so a first-time user can paste
// two GitHub secrets and ship; the comments point at the OIDC upgrade path.
function deployWorkflow(bp: Blueprint): string {
  const pm = bp.app.packageManager;
  const install =
    pm === 'npm'
      ? 'npm install'
      : pm === 'yarn'
        ? 'yarn install'
        : pm === 'pnpm'
          ? 'pnpm install'
          : 'bun install';
  const extraSetup =
    pm === 'pnpm'
      ? '      - uses: pnpm/action-setup@v4\n'
      : pm === 'bun'
        ? '      - uses: oven-sh/setup-bun@v2\n'
        : '';
  return `name: Deploy
# Add repo secrets AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY (IAM user), or
# switch to OIDC with aws-actions/configure-aws-credentials role-to-assume.
on:
  push:
    branches: [main]
concurrency: deploy-production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
${extraSetup}      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${bp.app.region}
      - run: ${install}
      - run: npx sst deploy --stage production
`;
}

function agentsMd(bp: Blueprint, files: GeneratedFile[]): string {
  const paths = files.map((f) => f.path);
  const has = (re: RegExp) => paths.some((p) => re.test(p));
  const list = (re: RegExp) => paths.filter((p) => re.test(p)).sort();

  const resources = bp.resources
    .map((r) => {
      const meta = AWS_CATALOG[r.kind];
      return `- **${r.name}** (${meta?.label ?? r.kind} — \`${meta?.component ?? r.kind}\`)`;
    })
    .join('\n');

  // The graph itself — what an AI needs to extend the app without mis-wiring
  // it. One line per connection: who talks to what, and what that intent means.
  const intentMeta = new Map(AWS_EDGE_INTENTS.map((i) => [i.intent, i]));
  const byId = new Map(bp.resources.map((r) => [r.id, r]));
  const dataFlow = bp.connections
    .map((c) => {
      const src = byId.get(c.source);
      const tgt = byId.get(c.target);
      if (!src || !tgt) return null;
      const meta = intentMeta.get(c.intent);
      const label = meta?.label ?? c.intent;
      const why = meta?.description ? ` — ${meta.description}` : '';
      return `- **${src.name}** ${label} **${tgt.name}** (\`${c.intent}\`)${why}`;
    })
    .filter((line): line is string => Boolean(line))
    .join('\n');

  const secrets = bp.resources.filter((r) => r.kind === 'secret' || r.kind === 'ai');
  const secretLines = secrets.length
    ? secrets.map((s) => `  - \`sst secret set ${s.name} <value>\``).join('\n')
    : '  - (none)';

  const envVars = collectAwsEnv(bp).filter((v) => v.name !== 'NEXT_PUBLIC_APP_NAME');
  const envLines = envVars.length
    ? envVars.map((v) => `  - \`${v.name}\`${v.hint ? ` — e.g. ${v.hint}` : ''}`).join('\n')
    : '  - (only NEXT_PUBLIC_APP_NAME)';

  const sections: string[] = [];
  if (has(/^app\/actions\//))
    sections.push(`- \`app/actions/*\` — \`"use server"\` actions (CRUD, uploads, enqueue).`);
  if (has(/^app\/[^/]+\/page\.tsx$/))
    sections.push(`- \`app/<resource>/\` — example list/create pages wired to the actions.`);
  if (has(/^app\/api\//)) sections.push(`- \`app/api/*/route.ts\` — HTTP route handlers.`);
  if (has(/^src\/workers\//))
    sections.push(
      `- \`src/workers/*\` — Lambda handlers (queue/bus/topic subscribers, cron, API routes).`,
    );
  if (has(/^lib\//))
    sections.push(`- \`lib/*\` — per-resource SDK helpers (read \`Resource.*\` from "sst").`);

  const hasContainer = bp.resources.some((r) => r.kind === 'service' || r.kind === 'task');
  const containerDevNote = hasContainer
    ? `\n> Containers (\`sst.aws.Service\`/\`Task\`) aren't deployed in \`sst dev\` either — SST runs
> each one's \`dev.command\` (\`npm run dev\`) locally and stubs its links, so the local
> process behaves exactly like the deployed task.`
    : '';

  return `# ${bp.app.name} — Architecture

> Generated by **SSTDREAM**. This is an **SST v4** app for **AWS**. Infrastructure lives in
> \`sst.config.ts\` (\`$config\` + \`sst.aws.*\`); runtime code reads linked resources via
> \`import { Resource } from "sst"\`. **Read this before extending the app.**

## Local development — \`sst dev\` (Live Lambda)

\`\`\`bash
npm install && npx sst dev
\`\`\`

**One command runs the whole app live against real AWS.** \`sst dev\` does *not* emulate the
cloud — it deploys stub Lambdas to your personal stage and proxies every real invocation
(API request, cron tick, queue message, S3 event, Step Functions step) back to the handler
running **on your machine**. Edit a function and it's live in **<1 second with no redeploy**,
with real IAM permissions and breakpoint debugging. Your Next.js dev server runs alongside it
from the same command.${containerDevNote}

> Each developer gets an isolated **stage** (your username by default), so \`sst dev\` never
> collides with a teammate or with \`production\`.

## Resources

${resources}

## Data flow (the design graph)

${dataFlow || '- (no connections — resources are standalone)'}

> The full machine-readable design is \`sstdream.design.json\` (nodes, edges, intents,
> props). Parse it before structural changes; keep it in sync by re-importing into
> SSTDREAM and re-exporting.

## Stages (dev / staging / production)

Every \`sst\` command takes a \`--stage\`, and **each stage is a fully isolated copy** of
this app (its own resources, secrets, and state). \`sst dev\` uses your **personal** stage
(your username) so you never collide with a teammate or with \`production\`.

\`\`\`bash
sst dev                                   # your personal dev stage (Live Lambda)
sst deploy --stage staging                # a shared staging copy
sst deploy --stage production             # production
\`\`\`

Make resources **stage-aware** by branching on \`$app.stage\` inside \`run()\` — the generated
\`app()\` already does this for \`removal\`/\`protect\`. Common patterns:

\`\`\`ts
const isProd = $app.stage === "production";

new sst.aws.Nextjs("Web", {
  // a custom domain only on production
  domain: isProd ? "app.example.com" : undefined,
});

new sst.aws.Service("Api", {
  cluster,
  // smaller/cheaper in non-prod stages
  cpu: isProd ? "1 vCPU" : "0.25 vCPU",
  scaling: isProd ? { min: 2, max: 8 } : { min: 1, max: 1 },
});
\`\`\`

**Secrets are per-stage** — set them once per stage:
\`sst secret set MySecret <value> --stage production\`.

## Secrets & environment

- **SST secrets** (set out-of-band, not in \`.env\`):
${secretLines}
- **\`.env\` variables** (see \`.env.example\`):
${envLines}

## Where things live

${sections.join('\n') || '- `sst.config.ts` — your infrastructure.'}

## Files of interest

${list(/^(lib|app\/actions|app\/api|src\/workers)\//)
  .map((p) => `- \`${p}\``)
  .join('\n')}

## How to extend

- **Add a field to a table:** edit the local \`Item\` type + the form in \`app/<table>/create-form.tsx\`.
- **Protect a server action/route:** add \`await requireUser()\` at the top (Clerk \`lib/auth-guard.ts\`), or your auth check.
- **Add a queue/bus/topic consumer:** add a Worker (subscribesTo) — it generates a \`src/workers/*\` handler.
- **Add an API route:** add a Worker with a \`route\` prop (handlesRoute → the HTTP API).
- **Deploy:** \`sst deploy --stage production\`. Set secrets first.

## Hard rules (do not break)

- \`sst.config.ts\`: no provider imports — use the \`sst.aws.*\` globals; declare resources inside \`run()\`.
- Server-only keys (\`*_SECRET\`, \`DATABASE_URL\`, API keys) stay server-side — never prefix with \`NEXT_PUBLIC_\`.
- Re-import \`sstdream.design.json\` into SSTDREAM to keep editing this visually.
`;
}

export function generateScaffold(
  bp: Blueprint,
  files: GeneratedFile[],
  deps: Record<string, string>,
  devDeps: Record<string, string> = {},
): GeneratedFile[] {
  const pageRoutes = files
    .map((f) => /^app\/([^/]+)\/page\.tsx$/.exec(f.path)?.[1])
    .filter((s): s is string => Boolean(s));
  const hasChat = files.some((f) => f.path === 'app/api/chat/route.ts');

  return [
    { path: 'package.json', content: packageJson(bp, deps, devDeps), language: 'json' },
    { path: 'tsconfig.json', content: tsconfigJson(), language: 'json' },
    { path: 'next.config.ts', content: nextConfig(), language: 'ts' },
    { path: '.gitignore', content: gitignore(), language: 'text' },
    { path: 'app/layout.tsx', content: layoutFile(bp), language: 'tsx' },
    { path: 'app/page.tsx', content: pageFile(bp, pageRoutes, hasChat), language: 'tsx' },
    { path: 'AGENTS.md', content: agentsMd(bp, files), language: 'md' },
    { path: '.github/workflows/deploy.yml', content: deployWorkflow(bp), language: 'text' },
  ];
}
