import type { Blueprint } from '@/lib/core/blueprint/types';
import type { GeneratedFile } from '@/lib/core/codegen/types';
import { kebabCase } from '@/lib/core/codegen/strings';
import { AWS_CATALOG } from '../catalog';
import { collectAwsEnv } from '../env';

// "New project" scaffold: turns the generated infra/runtime files into a complete,
// runnable Next.js 16 + SST v4 app (yarn install && sst dev) plus an AGENTS.md so
// Claude / any dev can open the export and finish it.

const sortObj = (o: Record<string, string>): Record<string, string> =>
  Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)));

function packageJson(bp: Blueprint, deps: Record<string, string>): string {
  const dependencies = sortObj({
    next: 'latest',
    react: 'latest',
    'react-dom': 'latest',
    ...deps,
  });
  const pkg = {
    name: kebabCase(bp.app.name) || 'sst-app',
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
      lint: 'eslint',
      'sst:dev': 'sst dev',
      deploy: 'sst deploy',
      remove: 'sst remove',
    },
    dependencies,
    devDependencies: sortObj({
      '@types/node': 'latest',
      '@types/react': 'latest',
      '@types/react-dom': 'latest',
      typescript: 'latest',
    }),
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

const tsconfigJson = (): string =>
  `${JSON.stringify(
    {
      compilerOptions: {
        target: 'ES2022',
        lib: ['dom', 'dom.iterable', 'esnext'],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: 'esnext',
        moduleResolution: 'bundler',
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: 'preserve',
        incremental: true,
        plugins: [{ name: 'next' }],
        paths: { '@/*': ['./*'] },
      },
      include: ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts', 'sst-env.d.ts'],
      exclude: ['node_modules'],
    },
    null,
    2,
  )}\n`;

const nextConfig = (): string =>
  `import type { NextConfig } from "next";

const nextConfig: NextConfig = {};

export default nextConfig;
`;

const gitignore = (): string =>
  `node_modules/
.next/
.sst/
.open-next/
out/
build/
*.tsbuildinfo
next-env.d.ts
sst-env.d.ts
.env*.local
.DS_Store
`;

function layoutFile(bp: Blueprint): string {
  const clerk = bp.resources.some((r) => r.kind === 'clerk');
  const meta = `export const metadata = { title: "${bp.app.name}", description: "Generated by SSTDREAM" };`;
  if (clerk) {
    return `import type { ReactNode } from "react";
import { ClerkProvider } from "@clerk/nextjs";

${meta}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
`;
  }
  return `import type { ReactNode } from "react";

${meta}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function pageFile(bp: Blueprint, pageRoutes: string[], hasChat: boolean): string {
  const items = [
    ...pageRoutes.map((seg) => `        <li><a href="/${seg}">/${seg}</a> — list + create</li>`),
    ...(hasChat
      ? ['        <li><code>POST /api/chat</code> — streaming Claude endpoint</li>']
      : []),
  ];
  const list = items.length
    ? `      <p>Wired to your resources:</p>
      <ul>
${items.join('\n')}
      </ul>`
    : `      <p>Add resources in SSTDREAM and re-export to scaffold pages here.</p>`;
  return `export default function Home() {
  return (
    <main style={{ maxWidth: 720, margin: "3rem auto", fontFamily: "system-ui", lineHeight: 1.6 }}>
      <h1>${bp.app.name}</h1>
      <p>Generated by SSTDREAM — a verified SST v4 app for AWS.</p>
${list}
      <p style={{ marginTop: 24, color: "#666" }}>
        See <code>AGENTS.md</code> for the architecture and how to extend it.
      </p>
    </main>
  );
}
`;
}

function agentsMd(bp: Blueprint, files: GeneratedFile[]): string {
  const paths = files.map((f) => f.path);
  const has = (re: RegExp) => paths.some((p) => re.test(p));
  const list = (re: RegExp) => paths.filter((p) => re.test(p)).sort();

  const resources = bp.resources
    .map((r) => {
      const meta = AWS_CATALOG[r.kind];
      return `- **${r.name}** (${meta?.label ?? r.kind} — \`${meta?.component ?? r.kind}\`)`;
    })
    .join('\n');

  const secrets = bp.resources.filter((r) => r.kind === 'secret' || r.kind === 'ai');
  const secretLines = secrets.length
    ? secrets.map((s) => `  - \`sst secret set ${s.name} <value>\``).join('\n')
    : '  - (none)';

  const envVars = collectAwsEnv(bp).filter((v) => v.name !== 'NEXT_PUBLIC_APP_NAME');
  const envLines = envVars.length
    ? envVars.map((v) => `  - \`${v.name}\`${v.hint ? ` — e.g. ${v.hint}` : ''}`).join('\n')
    : '  - (only NEXT_PUBLIC_APP_NAME)';

  const sections: string[] = [];
  if (has(/^app\/actions\//))
    sections.push(`- \`app/actions/*\` — \`"use server"\` actions (CRUD, uploads, enqueue).`);
  if (has(/^app\/[^/]+\/page\.tsx$/))
    sections.push(`- \`app/<resource>/\` — example list/create pages wired to the actions.`);
  if (has(/^app\/api\//)) sections.push(`- \`app/api/*/route.ts\` — HTTP route handlers.`);
  if (has(/^src\/workers\//))
    sections.push(
      `- \`src/workers/*\` — Lambda handlers (queue/bus/topic subscribers, cron, API routes).`,
    );
  if (has(/^lib\//))
    sections.push(`- \`lib/*\` — per-resource SDK helpers (read \`Resource.*\` from "sst").`);

  return `# ${bp.app.name} — Architecture

> Generated by **SSTDREAM**. This is an **SST v4** app for **AWS**. Infrastructure lives in
> \`sst.config.ts\` (\`$config\` + \`sst.aws.*\`); runtime code reads linked resources via
> \`import { Resource } from "sst"\`. **Read this before extending the app.**

## Resources

${resources}

## Secrets & environment

- **SST secrets** (set out-of-band, not in \`.env\`):
${secretLines}
- **\`.env\` variables** (see \`.env.example\`):
${envLines}

## Where things live

${sections.join('\n') || '- `sst.config.ts` — your infrastructure.'}

## Files of interest

${list(/^(lib|app\/actions|app\/api|src\/workers)\//)
  .map((p) => `- \`${p}\``)
  .join('\n')}

## How to extend

- **Add a field to a table:** edit the local \`Item\` type + the form in \`app/<table>/create-form.tsx\`.
- **Protect a server action/route:** add \`await requireUser()\` at the top (Clerk \`lib/auth-guard.ts\`), or your auth check.
- **Add a queue/bus/topic consumer:** add a Worker (subscribesTo) — it generates a \`src/workers/*\` handler.
- **Add an API route:** add a Worker with a \`route\` prop (handlesRoute → the HTTP API).
- **Deploy:** \`sst deploy --stage production\`. Set secrets first.

## Hard rules (do not break)

- \`sst.config.ts\`: no provider imports — use the \`sst.aws.*\` globals; declare resources inside \`run()\`.
- Server-only keys (\`*_SECRET\`, \`DATABASE_URL\`, API keys) stay server-side — never prefix with \`NEXT_PUBLIC_\`.
- Re-import \`sstdream.design.json\` into SSTDREAM to keep editing this visually.
`;
}

export function generateScaffold(
  bp: Blueprint,
  files: GeneratedFile[],
  deps: Record<string, string>,
): GeneratedFile[] {
  const pageRoutes = files
    .map((f) => /^app\/([^/]+)\/page\.tsx$/.exec(f.path)?.[1])
    .filter((s): s is string => Boolean(s));
  const hasChat = files.some((f) => f.path === 'app/api/chat/route.ts');

  return [
    { path: 'package.json', content: packageJson(bp, deps), language: 'json' },
    { path: 'tsconfig.json', content: tsconfigJson(), language: 'json' },
    { path: 'next.config.ts', content: nextConfig(), language: 'ts' },
    { path: '.gitignore', content: gitignore(), language: 'text' },
    { path: 'app/layout.tsx', content: layoutFile(bp), language: 'tsx' },
    { path: 'app/page.tsx', content: pageFile(bp, pageRoutes, hasChat), language: 'tsx' },
    { path: 'AGENTS.md', content: agentsMd(bp, files), language: 'md' },
  ];
}
