import type { CanvasNode, CanvasEdge } from '@/lib/canvas/types';
import type { TemplateMeta } from './types';

// Builders to keep the AWS template snapshots terse and readable.
const n = (
  id: string,
  kind: string,
  name: string,
  x: number,
  y: number,
  props: Record<string, unknown> = {},
): CanvasNode => ({ id, kind, name, props, position: { x, y } });
const e = (id: string, source: string, target: string, intent: string): CanvasEdge => ({
  id,
  source,
  target,
  intent,
});

const aws = (
  id: string,
  name: string,
  description: string,
  tags: string[],
  appName: string,
  nodes: CanvasNode[],
  edges: CanvasEdge[],
): TemplateMeta => ({
  id,
  name,
  description,
  target: 'aws-sst-v4',
  tags,
  app: { name: appName, region: 'us-east-1', packageManager: 'yarn' },
  snapshot: { nodes, edges },
});

export const AWS_TEMPLATES: TemplateMeta[] = [
  aws(
    'aws-event-analytics',
    'Event-Driven Analytics',
    'Fan-out app events to an SNS topic, warehouse them in Aurora Serverless v2, and enrich via a third-party API. Covers the eventing + relational-warehouse + external-API trio.',
    ['Analytics', 'Events'],
    'event-analytics',
    [
      n('nextjs_1', 'nextjs', 'Web', 60, 200),
      n('snstopic_2', 'snstopic', 'Events', 360, 60),
      n('aurora_3', 'aurora', 'Warehouse', 360, 200),
      n('externalApi_4', 'externalApi', 'Enrichment', 360, 340),
    ],
    [
      e('edge_5', 'nextjs_1', 'snstopic_2', 'publishesTo'),
      e('edge_6', 'nextjs_1', 'aurora_3', 'queriesDb'),
      e('edge_7', 'nextjs_1', 'externalApi_4', 'callsApi'),
    ],
  ),
  aws(
    'aws-full-saas',
    'Full SaaS',
    'The kitchen sink: Clerk auth, Stripe payments, DynamoDB CRUD, SES email, S3 uploads, and a daily cron — everything wired.',
    ['SaaS', 'Flagship', 'Auth', 'Payments'],
    'full-saas',
    [
      n('nextjs_1', 'nextjs', 'Web', 60, 220),
      n('clerk_2', 'clerk', 'Clerk', 340, 40),
      n('stripe_3', 'stripe', 'Stripe', 340, 140),
      n('dynamo_4', 'dynamo', 'Projects', 340, 240),
      n('email_5', 'email', 'Mailer', 340, 340),
      n('bucket_6', 'bucket', 'Uploads', 340, 440),
      n('cron_7', 'cron', 'DailyDigest', 60, 440, { schedule: 'cron(0 13 * * ? *)' }),
      n('worker_8', 'worker', 'SendDigest', 620, 380),
    ],
    [
      e('edge_9', 'nextjs_1', 'clerk_2', 'usesAuth'),
      e('edge_10', 'nextjs_1', 'stripe_3', 'usesStripe'),
      e('edge_11', 'nextjs_1', 'dynamo_4', 'writesTo'),
      e('edge_12', 'nextjs_1', 'email_5', 'sendsEmail'),
      e('edge_13', 'nextjs_1', 'bucket_6', 'uploadsTo'),
      e('edge_14', 'cron_7', 'worker_8', 'invokes'),
      e('edge_15', 'worker_8', 'dynamo_4', 'writesTo'),
      e('edge_16', 'worker_8', 'email_5', 'sendsEmail'),
    ],
  ),
  aws(
    'aws-ai-chat',
    'AI Chat App',
    'Streaming Claude chat (claude-opus-4-8) with history in DynamoDB. The flagship AI starter.',
    ['AI', 'Flagship'],
    'ai-chat-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 160),
      n('ai_2', 'ai', 'AnthropicKey', 380, 80, { model: 'claude-opus-4-8' }),
      n('dynamo_3', 'dynamo', 'ChatHistory', 380, 240),
    ],
    [e('edge_4', 'nextjs_1', 'ai_2', 'usesAI'), e('edge_5', 'nextjs_1', 'dynamo_3', 'writesTo')],
  ),
  aws(
    'aws-clerk-saas',
    'Clerk SaaS',
    'Drop-in Clerk auth + Stripe + MongoDB. The easiest full SaaS starter.',
    ['SaaS', 'Auth', 'Flagship'],
    'clerk-saas',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 180),
      n('clerk_2', 'clerk', 'Clerk', 380, 60),
      n('stripe_3', 'stripe', 'Stripe', 380, 180),
      n('mongodb_4', 'mongodb', 'Mongo', 380, 300),
    ],
    [
      e('edge_5', 'nextjs_1', 'clerk_2', 'usesAuth'),
      e('edge_6', 'nextjs_1', 'stripe_3', 'usesStripe'),
      e('edge_7', 'nextjs_1', 'mongodb_4', 'queriesMongo'),
    ],
  ),
  aws(
    'aws-cognito-app',
    'Cognito App',
    'AWS-native auth (Cognito user pool) + a DynamoDB table.',
    ['Auth'],
    'cognito-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 160),
      n('cognito_2', 'cognito', 'AuthPool', 380, 80),
      n('dynamo_3', 'dynamo', 'AppData', 380, 240),
    ],
    [
      e('edge_4', 'nextjs_1', 'cognito_2', 'usesCognito'),
      e('edge_5', 'nextjs_1', 'dynamo_3', 'writesTo'),
    ],
  ),
  aws(
    'aws-starter',
    'Next.js Starter',
    'A bare Next.js app on AWS — add resources as you go.',
    ['Starter'],
    'nextjs-starter',
    [n('nextjs_1', 'nextjs', 'Web', 200, 160)],
    [],
  ),
  aws(
    'aws-upload',
    'File Upload',
    'Next.js + S3 with presigned uploads.',
    ['Storage'],
    'file-upload-app',
    [n('nextjs_1', 'nextjs', 'Web', 80, 160), n('bucket_2', 'bucket', 'Uploads', 380, 160)],
    [e('edge_3', 'nextjs_1', 'bucket_2', 'uploadsTo')],
  ),
  aws(
    'aws-blog',
    'Blog',
    'Posts in DynamoDB, media in S3.',
    ['Content'],
    'blog-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 160),
      n('dynamo_2', 'dynamo', 'Posts', 380, 80),
      n('bucket_3', 'bucket', 'Media', 380, 240),
    ],
    [
      e('edge_4', 'nextjs_1', 'dynamo_2', 'writesTo'),
      e('edge_5', 'nextjs_1', 'bucket_3', 'uploadsTo'),
    ],
  ),
  aws(
    'aws-cms',
    'CMS',
    'Content store, asset bucket, async reindex worker, admin secret.',
    ['Content'],
    'cms-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 60, 200),
      n('dynamo_2', 'dynamo', 'Content', 360, 60),
      n('bucket_3', 'bucket', 'Assets', 360, 180),
      n('queue_4', 'queue', 'Reindex', 360, 300),
      n('worker_5', 'worker', 'Indexer', 640, 300),
      n('secret_6', 'secret', 'AdminToken', 60, 360),
    ],
    [
      e('edge_7', 'nextjs_1', 'dynamo_2', 'writesTo'),
      e('edge_8', 'nextjs_1', 'bucket_3', 'uploadsTo'),
      e('edge_9', 'nextjs_1', 'queue_4', 'publishesTo'),
      e('edge_10', 'worker_5', 'queue_4', 'subscribesTo'),
      e('edge_11', 'worker_5', 'dynamo_2', 'writesTo'),
      e('edge_12', 'nextjs_1', 'secret_6', 'usesSecret'),
    ],
  ),
  aws(
    'aws-lms',
    'LMS',
    'Courses + progress tables, video bucket, transcode worker.',
    ['Content', 'Media'],
    'lms-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 60, 220),
      n('dynamo_2', 'dynamo', 'Courses', 360, 60),
      n('dynamo_3', 'dynamo', 'Progress', 360, 160),
      n('bucket_4', 'bucket', 'Videos', 360, 280),
      n('queue_5', 'queue', 'Transcode', 360, 400),
      n('worker_6', 'worker', 'Transcoder', 640, 400),
    ],
    [
      e('edge_7', 'nextjs_1', 'dynamo_2', 'writesTo'),
      e('edge_8', 'nextjs_1', 'dynamo_3', 'writesTo'),
      e('edge_9', 'nextjs_1', 'bucket_4', 'uploadsTo'),
      e('edge_10', 'nextjs_1', 'queue_5', 'publishesTo'),
      e('edge_11', 'worker_6', 'queue_5', 'subscribesTo'),
      e('edge_12', 'worker_6', 'dynamo_2', 'writesTo'),
    ],
  ),
  aws(
    'aws-marketplace',
    'Marketplace',
    'Listings, images, order queue + fulfillment worker, Stripe secret.',
    ['SaaS', 'Commerce'],
    'marketplace-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 60, 200),
      n('dynamo_2', 'dynamo', 'Listings', 360, 60),
      n('bucket_3', 'bucket', 'Images', 360, 180),
      n('queue_4', 'queue', 'Orders', 360, 300),
      n('worker_5', 'worker', 'FulfillOrder', 640, 300),
      n('secret_6', 'secret', 'StripeKey', 60, 360),
    ],
    [
      e('edge_7', 'nextjs_1', 'dynamo_2', 'writesTo'),
      e('edge_8', 'nextjs_1', 'bucket_3', 'uploadsTo'),
      e('edge_9', 'nextjs_1', 'queue_4', 'publishesTo'),
      e('edge_10', 'worker_5', 'queue_4', 'subscribesTo'),
      e('edge_11', 'worker_5', 'dynamo_2', 'writesTo'),
      e('edge_12', 'nextjs_1', 'secret_6', 'usesSecret'),
    ],
  ),
  aws(
    'aws-relational-saas',
    'Relational SaaS',
    'RDS Postgres (VPC auto-generated), transactional email, Stripe secret.',
    ['SaaS', 'Database'],
    'relational-saas',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 180),
      n('postgres_2', 'postgres', 'Database', 380, 60),
      n('email_3', 'email', 'Mailer', 380, 180, { sender: 'noreply@example.com' }),
      n('secret_4', 'secret', 'StripeKey', 80, 340),
    ],
    [
      e('edge_5', 'nextjs_1', 'postgres_2', 'queriesDb'),
      e('edge_6', 'nextjs_1', 'email_3', 'sendsEmail'),
      e('edge_7', 'nextjs_1', 'secret_4', 'usesSecret'),
    ],
  ),
  aws(
    'aws-stripe-saas',
    'Stripe SaaS',
    'Clerk auth + Stripe payments (webhook) + MongoDB + uploads.',
    ['SaaS', 'Payments', 'Auth'],
    'stripe-saas',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 200),
      n('clerk_2', 'clerk', 'Clerk', 380, 40),
      n('stripe_3', 'stripe', 'Stripe', 380, 150),
      n('mongodb_4', 'mongodb', 'Mongo', 380, 260),
      n('bucket_5', 'bucket', 'Uploads', 380, 370),
    ],
    [
      e('edge_6', 'nextjs_1', 'clerk_2', 'usesAuth'),
      e('edge_7', 'nextjs_1', 'stripe_3', 'usesStripe'),
      e('edge_8', 'nextjs_1', 'mongodb_4', 'queriesMongo'),
      e('edge_9', 'nextjs_1', 'bucket_5', 'uploadsTo'),
    ],
  ),
  aws(
    'aws-events',
    'Event-Driven',
    'EventBridge bus: the app publishes events, a worker subscribes and logs them.',
    ['Events'],
    'event-driven-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 160),
      n('bus_2', 'bus', 'Events', 380, 80),
      n('worker_3', 'worker', 'Handler', 660, 80),
      n('dynamo_4', 'dynamo', 'Log', 660, 260),
    ],
    [
      e('edge_5', 'nextjs_1', 'bus_2', 'publishesTo'),
      e('edge_6', 'worker_3', 'bus_2', 'subscribesTo'),
      e('edge_7', 'worker_3', 'dynamo_4', 'writesTo'),
    ],
  ),
  aws(
    'aws-webhook-api',
    'Webhook API',
    'HTTP API Gateway with a Stripe webhook route handler that logs to DynamoDB.',
    ['API', 'Payments'],
    'webhook-api',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 160),
      n('apigatewayv2_2', 'apigatewayv2', 'Api', 380, 80),
      n('worker_3', 'worker', 'StripeWebhook', 660, 80, { route: 'POST /webhooks/stripe' }),
      n('dynamo_4', 'dynamo', 'Events', 660, 260),
    ],
    [
      e('edge_5', 'worker_3', 'apigatewayv2_2', 'handlesRoute'),
      e('edge_6', 'worker_3', 'dynamo_4', 'writesTo'),
    ],
  ),
  aws(
    'aws-image-pipeline',
    'Image Pipeline',
    'Uploads to S3 trigger a worker (bucket.notify) that processes and logs to DynamoDB.',
    ['Storage', 'Events'],
    'image-pipeline',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 160),
      n('bucket_2', 'bucket', 'Uploads', 360, 80),
      n('worker_3', 'worker', 'Resize', 640, 80),
      n('dynamo_4', 'dynamo', 'Images', 640, 260),
    ],
    [
      e('edge_5', 'nextjs_1', 'bucket_2', 'uploadsTo'),
      e('edge_6', 'worker_3', 'bucket_2', 'handlesBucketEvents'),
      e('edge_7', 'worker_3', 'dynamo_4', 'writesTo'),
    ],
  ),
  aws(
    'aws-cdn-router',
    'CDN Router',
    'A Router front-door (custom domain) serving a static docs site at /docs and a bucket at /assets.',
    ['Network', 'CDN'],
    'cdn-router',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 200),
      n('router_2', 'router', 'Router', 360, 80, { domain: 'example.com' }),
      n('staticsite_3', 'staticsite', 'Docs', 640, 40, { routePath: '/docs' }),
      n('bucket_4', 'bucket', 'Assets', 640, 200, { access: 'cloudfront', routePath: '/assets' }),
    ],
    [
      e('edge_5', 'router_2', 'bucket_4', 'routesBucket'),
      e('edge_6', 'staticsite_3', 'router_2', 'routedBy'),
    ],
  ),
  aws(
    'aws-marketing',
    'Marketing Site',
    'Leads table + a weekly report cron.',
    ['Marketing'],
    'marketing-app',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 160),
      n('dynamo_2', 'dynamo', 'Leads', 380, 80),
      n('cron_3', 'cron', 'WeeklyReport', 80, 320, { schedule: 'cron(0 13 ? * MON *)' }),
      n('worker_4', 'worker', 'SendReport', 380, 320),
    ],
    [
      e('edge_5', 'nextjs_1', 'dynamo_2', 'writesTo'),
      e('edge_6', 'cron_3', 'worker_4', 'invokes'),
      e('edge_7', 'worker_4', 'dynamo_2', 'readsFrom'),
    ],
  ),
  aws(
    'aws-order-workflow',
    'Durable Order Workflow (Step Functions)',
    'A Next.js app starts a durable Step Functions execution (Validate → Process → Done) for each order, with each step a Lambda. Orders persist in DynamoDB. Survives retries and long-running waits.',
    ['Workflow', 'Flagship', 'Durable'],
    'order-workflow',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 180),
      n('stepFunctions_2', 'stepFunctions', 'OrderFlow', 400, 80, { type: 'standard' }),
      n('dynamo_3', 'dynamo', 'Orders', 400, 300),
    ],
    [
      e('edge_4', 'nextjs_1', 'stepFunctions_2', 'startsWorkflow'),
      e('edge_5', 'nextjs_1', 'dynamo_3', 'writesTo'),
    ],
  ),
  aws(
    'aws-realtime-chat',
    'Realtime Chat (WebSockets)',
    'Live WebSocket pub/sub over AWS IoT: a custom authorizer guards every connection, the Next.js app publishes messages, and a subscriber Lambda processes them. History persists in DynamoDB.',
    ['Realtime', 'Flagship', 'WebSockets'],
    'realtime-chat',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 180),
      n('realtime_2', 'realtime', 'Realtime', 400, 80),
      n('dynamo_3', 'dynamo', 'Messages', 400, 300),
    ],
    [
      e('edge_4', 'nextjs_1', 'realtime_2', 'usesRealtime'),
      e('edge_5', 'nextjs_1', 'dynamo_3', 'writesTo'),
    ],
  ),
  aws(
    'aws-batch-task',
    'On-Demand Job Runner (Fargate Task)',
    'A Next.js app kicks off a one-off Fargate Task (heavy batch work — video transcode, report build) with task.run(), and the task writes results to S3. No idle cost: the container only runs when invoked.',
    ['Containers', 'Batch', 'Jobs'],
    'job-runner',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 180),
      n('task_2', 'task', 'ProcessJob', 400, 100, { cpu: '1 vCPU', memory: '2 GB' }),
      n('bucket_3', 'bucket', 'Results', 400, 320),
    ],
    [e('edge_4', 'nextjs_1', 'task_2', 'runsTask'), e('edge_5', 'task_2', 'bucket_3', 'readsFrom')],
  ),
  aws(
    'aws-fargate-service',
    'Containerized Service (Fargate)',
    'A long-running container on ECS Fargate behind a load balancer, talking to Postgres and a Redis cache. SST generates the Cluster, the VPC (with fck-nat), and a starter Dockerfile. `sst dev` runs the container locally.',
    ['Containers', 'Flagship', 'Fargate'],
    'fargate-service',
    [
      n('service_1', 'service', 'Api', 80, 200, { cpu: '0.5 vCPU', memory: '1 GB', port: 3000 }),
      n('postgres_2', 'postgres', 'Database', 400, 100),
      n('redis_3', 'redis', 'Cache', 400, 320),
    ],
    [
      e('edge_4', 'service_1', 'postgres_2', 'queriesDb'),
      e('edge_5', 'service_1', 'redis_3', 'usesCache'),
    ],
  ),
  aws(
    'aws-graphql-api',
    'GraphQL API (AppSync)',
    'A managed GraphQL API with AppSync: a starter schema, a Lambda resolver that reads/writes a DynamoDB table, and a Next.js app that queries it through a typed gql() helper.',
    ['API', 'GraphQL', 'Flagship'],
    'graphql-api',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 180),
      n('appsync_2', 'appsync', 'Graph', 400, 100),
      n('dynamo_3', 'dynamo', 'Users', 700, 100),
    ],
    [
      e('edge_4', 'nextjs_1', 'appsync_2', 'consumesGraphQL'),
      e('edge_5', 'appsync_2', 'dynamo_3', 'resolvesFrom'),
    ],
  ),
  aws(
    'aws-openauth-saas',
    'OpenAuth SaaS (self-hosted auth)',
    'Self-hosted auth with OpenAuth (sst.aws.Auth): the issuer runs on Lambda with auto-provisioned DynamoDB storage, and the Next.js app gets the full login/callback/verify flow. Your auth, your data — no third-party auth bill.',
    ['SaaS', 'Auth', 'Flagship'],
    'openauth-saas',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 180),
      n('openauth_2', 'openauth', 'Auth', 400, 80),
      n('dynamo_3', 'dynamo', 'Users', 400, 300),
    ],
    [
      e('edge_4', 'nextjs_1', 'openauth_2', 'usesOpenAuth'),
      e('edge_5', 'nextjs_1', 'dynamo_3', 'writesTo'),
    ],
  ),
  aws(
    'aws-cached-api',
    'Cached API + Redis',
    'A read-heavy API: Postgres as the source of truth, ElastiCache Redis (cluster-mode, TLS) as the cache. Both share one auto-generated VPC; fck-nat keeps Lambdas online.',
    ['API', 'Performance', 'Cache'],
    'cached-api',
    [
      n('nextjs_1', 'nextjs', 'Web', 80, 200),
      n('redis_2', 'redis', 'Cache', 400, 100),
      n('postgres_3', 'postgres', 'Database', 400, 320),
    ],
    [
      e('edge_4', 'nextjs_1', 'redis_2', 'usesCache'),
      e('edge_5', 'nextjs_1', 'postgres_3', 'queriesDb'),
    ],
  ),
];
