import type { CanvasNode, CanvasEdge } from '@/lib/canvas/types';
import type { TemplateMeta } from './types';

// Builders to keep the Vercel template snapshots terse and readable. Every design
// uses only the Vercel catalog kinds and valid edge intents, and validates clean
// (templates.test.ts enforces zero errors + >0 generated files per template).
const n = (
  id: string,
  kind: string,
  name: string,
  x: number,
  y: number,
  props: Record<string, unknown> = {},
): CanvasNode => ({ id, kind, name, props, position: { x, y } });
const e = (id: string, source: string, target: string, intent: string): CanvasEdge => ({
  id,
  source,
  target,
  intent,
});

const vercel = (
  id: string,
  name: string,
  description: string,
  tags: string[],
  appName: string,
  nodes: CanvasNode[],
  edges: CanvasEdge[],
): TemplateMeta => ({
  id,
  name,
  description,
  target: 'vercel',
  tags,
  app: { name: appName, region: 'iad1', packageManager: 'yarn' },
  snapshot: { nodes, edges },
});

const DAILY = { schedule: '0 5 * * *' };

export const VERCEL_TEMPLATES: TemplateMeta[] = [
  vercel(
    'vercel-blog',
    'Blog / CMS',
    'Next.js blog on Vercel: Neon Postgres for posts, Vercel Blob for images.',
    ['Content', 'Starter'],
    'vercel-blog',
    [
      n('app_1', 'app', 'Web', 60, 160),
      n('postgres_2', 'postgres', 'Db', 360, 80),
      n('blob_3', 'blob', 'Media', 360, 240),
    ],
    [e('e1', 'app_1', 'postgres_2', 'writesToService'), e('e2', 'app_1', 'blob_3', 'storesFileIn')],
  ),
  vercel(
    'vercel-ecommerce',
    'E-commerce Store',
    'Storefront with Postgres catalog, Blob product images, an order queue + consumer, a Stripe webhook, and Resend receipts.',
    ['Commerce', 'Flagship', 'Payments'],
    'vercel-store',
    [
      n('app_1', 'app', 'Web', 60, 220),
      n('postgres_2', 'postgres', 'Catalog', 360, 60),
      n('blob_3', 'blob', 'ProductImages', 360, 160),
      n('queue_4', 'queue', 'Orders', 360, 280),
      n('consumer_5', 'consumer', 'FulfillOrder', 640, 280),
      n('email_6', 'email', 'Mailer', 360, 380),
      n('webhook_7', 'webhook', 'StripeHook', 60, 60),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'blob_3', 'storesFileIn'),
      e('e3', 'app_1', 'queue_4', 'enqueuesTo'),
      e('e4', 'queue_4', 'consumer_5', 'consumedBy'),
      e('e5', 'app_1', 'email_6', 'sendsEmailThrough'),
    ],
  ),
  vercel(
    'vercel-saas-pro',
    'SaaS Pro',
    'Multi-tenant SaaS: Postgres data, Upstash Redis cache, transactional email, and a daily digest cron.',
    ['SaaS'],
    'vercel-saas-pro',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('postgres_2', 'postgres', 'Db', 360, 80),
      n('redis_3', 'redis', 'Cache', 360, 200),
      n('email_4', 'email', 'Mailer', 360, 320),
      n('cron_5', 'cron', 'DailyDigest', 60, 360, DAILY),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'redis_3', 'writesToService'),
      e('e3', 'app_1', 'email_4', 'sendsEmailThrough'),
    ],
  ),
  vercel(
    'vercel-marketing',
    'Marketing Site',
    'A fast marketing site with a Resend contact form and a weekly newsletter cron. Zero-config deploy.',
    ['Marketing', 'Starter'],
    'vercel-marketing',
    [
      n('app_1', 'app', 'Web', 60, 160),
      n('email_2', 'email', 'ContactForm', 360, 100),
      n('cron_3', 'cron', 'Newsletter', 360, 240, DAILY),
    ],
    [e('e1', 'app_1', 'email_2', 'sendsEmailThrough')],
  ),
  vercel(
    'vercel-image-pipeline',
    'Image Pipeline',
    'Upload to Vercel Blob, enqueue a resize job, and process it in a push-mode queue consumer.',
    ['Pipeline'],
    'vercel-images',
    [
      n('app_1', 'app', 'Web', 60, 180),
      n('blob_2', 'blob', 'Uploads', 360, 80),
      n('queue_3', 'queue', 'ResizeJobs', 360, 240),
      n('consumer_4', 'consumer', 'ResizeImage', 640, 240),
    ],
    [
      e('e1', 'app_1', 'blob_2', 'storesFileIn'),
      e('e2', 'app_1', 'queue_3', 'enqueuesTo'),
      e('e3', 'queue_3', 'consumer_4', 'consumedBy'),
    ],
  ),
  vercel(
    'vercel-job-board',
    'Job Board',
    'Listings in Postgres, company logos in Blob, an expiry cron, and Resend alerts.',
    ['Content', 'Marketplace'],
    'vercel-jobs',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('postgres_2', 'postgres', 'Listings', 360, 80),
      n('blob_3', 'blob', 'Logos', 360, 200),
      n('email_4', 'email', 'Notifier', 360, 320),
      n('cron_5', 'cron', 'ExpireListings', 60, 360, DAILY),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'blob_3', 'storesFileIn'),
      e('e3', 'app_1', 'email_4', 'sendsEmailThrough'),
    ],
  ),
  vercel(
    'vercel-realtime',
    'Realtime / Presence',
    'Postgres for durable data plus Upstash Redis for presence and live counters.',
    ['Realtime'],
    'vercel-realtime',
    [
      n('app_1', 'app', 'Web', 60, 160),
      n('postgres_2', 'postgres', 'Db', 360, 80),
      n('redis_3', 'redis', 'Presence', 360, 240),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'redis_3', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-webhook-hub',
    'Webhook Hub',
    'Receive a signed webhook, enqueue it, and process events in a consumer; an event log in Postgres.',
    ['Integration', 'Webhooks'],
    'vercel-webhooks',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('webhook_2', 'webhook', 'IncomingHook', 60, 60, { provider: 'generic' }),
      n('queue_3', 'queue', 'Events', 360, 200),
      n('consumer_4', 'consumer', 'ProcessEvent', 640, 200),
      n('postgres_5', 'postgres', 'EventLog', 360, 60),
    ],
    [
      e('e1', 'app_1', 'queue_3', 'enqueuesTo'),
      e('e2', 'queue_3', 'consumer_4', 'consumedBy'),
      e('e3', 'app_1', 'postgres_5', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-newsletter',
    'Newsletter',
    'Subscribers in Postgres, a scheduled send cron, and Resend delivery.',
    ['Marketing', 'Email'],
    'vercel-newsletter',
    [
      n('app_1', 'app', 'Web', 60, 180),
      n('postgres_2', 'postgres', 'Subscribers', 360, 80),
      n('email_3', 'email', 'Sender', 360, 240),
      n('cron_4', 'cron', 'SendIssue', 60, 340, DAILY),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'email_3', 'sendsEmailThrough'),
    ],
  ),
  vercel(
    'vercel-background-jobs',
    'Background Jobs',
    'A Vercel Queue + push-mode consumer for async work, with Upstash Redis for locks/dedupe.',
    ['Jobs', 'Pipeline'],
    'vercel-jobs-runner',
    [
      n('app_1', 'app', 'Web', 60, 180),
      n('queue_2', 'queue', 'Tasks', 360, 120),
      n('consumer_3', 'consumer', 'RunTask', 640, 120),
      n('redis_4', 'redis', 'Locks', 360, 260),
    ],
    [
      e('e1', 'app_1', 'queue_2', 'enqueuesTo'),
      e('e2', 'queue_2', 'consumer_3', 'consumedBy'),
      e('e3', 'app_1', 'redis_4', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-headless-cms',
    'Headless CMS',
    'Content in Postgres, media in Blob, and an Upstash Redis read cache for fast delivery.',
    ['Content', 'CMS'],
    'vercel-cms',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('postgres_2', 'postgres', 'Content', 360, 80),
      n('blob_3', 'blob', 'Assets', 360, 200),
      n('redis_4', 'redis', 'Cache', 360, 320),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'blob_3', 'storesFileIn'),
      e('e3', 'app_1', 'redis_4', 'readsFromService'),
    ],
  ),
  vercel(
    'vercel-api-backend',
    'API Backend',
    'A JSON API with Postgres storage, Upstash Redis rate-limiting, and a partner webhook.',
    ['API', 'Backend'],
    'vercel-api',
    [
      n('app_1', 'app', 'Web', 60, 180),
      n('postgres_2', 'postgres', 'Db', 360, 80),
      n('redis_3', 'redis', 'RateLimit', 360, 220),
      n('webhook_4', 'webhook', 'PartnerHook', 60, 60, { provider: 'generic' }),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'redis_3', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-feature-flags',
    'Feature Flags',
    'Instant feature flags from Edge Config (read at the edge with no DB round-trip), data in Postgres.',
    ['Edge Config', 'Starter'],
    'vercel-flags',
    [
      n('app_1', 'app', 'Web', 60, 160),
      n('edgeConfig_2', 'edgeConfig', 'Flags', 360, 80),
      n('postgres_3', 'postgres', 'Db', 360, 240),
    ],
    [
      e('e1', 'app_1', 'edgeConfig_2', 'readsConfig'),
      e('e2', 'app_1', 'postgres_3', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-weather',
    'Weather App',
    'Calls an external weather API through a typed fetch helper, with an Upstash Redis response cache.',
    ['API', 'Starter'],
    'vercel-weather',
    [
      n('app_1', 'app', 'Web', 60, 160),
      n('externalApi_2', 'externalApi', 'Weather', 360, 80, {
        baseUrlEnv: 'WEATHER_BASE_URL',
        keyEnv: 'WEATHER_API_KEY',
      }),
      n('redis_3', 'redis', 'Cache', 360, 240),
    ],
    [e('e1', 'app_1', 'externalApi_2', 'callsApi'), e('e2', 'app_1', 'redis_3', 'writesToService')],
  ),
  vercel(
    'vercel-analytics-saas',
    'Analytics SaaS',
    'A SaaS with Web Analytics + Speed Insights wired into the layout, Postgres data, and email.',
    ['SaaS', 'Observability'],
    'vercel-analytics-saas',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('postgres_2', 'postgres', 'Db', 360, 80),
      n('email_3', 'email', 'Mailer', 360, 200),
      n('analytics_4', 'analytics', 'Analytics', 60, 60),
      n('speedInsights_5', 'speedInsights', 'SpeedInsights', 60, 340),
    ],
    [
      e('e1', 'app_1', 'postgres_2', 'writesToService'),
      e('e2', 'app_1', 'email_3', 'sendsEmailThrough'),
    ],
  ),
  vercel(
    'vercel-ai-proxy',
    'AI Proxy / Gateway',
    'A typed proxy to an external AI provider (your code calls it — the builder makes no AI calls), with Redis rate-limiting and model config in Edge Config.',
    ['API', 'AI'],
    'vercel-ai-proxy',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('externalApi_2', 'externalApi', 'AiProvider', 360, 80, {
        baseUrlEnv: 'AI_BASE_URL',
        keyEnv: 'AI_API_KEY',
      }),
      n('redis_3', 'redis', 'RateLimit', 360, 200),
      n('edgeConfig_4', 'edgeConfig', 'ModelConfig', 360, 320),
    ],
    [
      e('e1', 'app_1', 'externalApi_2', 'callsApi'),
      e('e2', 'app_1', 'redis_3', 'writesToService'),
      e('e3', 'app_1', 'edgeConfig_4', 'readsConfig'),
    ],
  ),
  vercel(
    'vercel-link-shortener',
    'Link Shortener',
    'Short links in Upstash Redis, click analytics in Postgres, and Web Analytics on the redirect.',
    ['API', 'Starter'],
    'vercel-shortener',
    [
      n('app_1', 'app', 'Web', 60, 180),
      n('redis_2', 'redis', 'Links', 360, 80),
      n('postgres_3', 'postgres', 'Clicks', 360, 220),
      n('analytics_4', 'analytics', 'Analytics', 60, 60),
    ],
    [
      e('e1', 'app_1', 'redis_2', 'writesToService'),
      e('e2', 'app_1', 'postgres_3', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-status-monitor',
    'Status Monitor',
    'A cron pings an external health API on a schedule and emails on failure; Speed Insights on the dashboard.',
    ['Monitoring', 'Jobs'],
    'vercel-status',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('externalApi_2', 'externalApi', 'HealthApi', 360, 80, {
        baseUrlEnv: 'HEALTH_BASE_URL',
        keyEnv: 'HEALTH_API_KEY',
      }),
      n('email_3', 'email', 'Alerts', 360, 220),
      n('cron_4', 'cron', 'Ping', 60, 60, DAILY),
      n('speedInsights_5', 'speedInsights', 'SpeedInsights', 60, 360),
    ],
    [
      e('e1', 'app_1', 'externalApi_2', 'callsApi'),
      e('e2', 'app_1', 'email_3', 'sendsEmailThrough'),
    ],
  ),
  vercel(
    'vercel-ai-chat',
    'AI Chat SaaS',
    'Streaming AI chat through the Vercel AI Gateway (you run it — the builder makes no AI calls), with chat history in Postgres and Upstash Redis rate-limiting.',
    ['AI', 'Flagship', 'SaaS'],
    'vercel-ai-chat',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('aiGateway_2', 'aiGateway', 'Chat', 360, 80, { model: 'openai/gpt-4o' }),
      n('postgres_3', 'postgres', 'History', 360, 220),
      n('redis_4', 'redis', 'RateLimit', 360, 340),
      n('analytics_5', 'analytics', 'Analytics', 60, 60),
    ],
    [
      e('e1', 'app_1', 'postgres_3', 'writesToService'),
      e('e2', 'app_1', 'redis_4', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-social-cards',
    'Viral Social Cards',
    'Dynamic Open Graph images at the edge (next/og) for shareable cards, with media in Blob and Web Analytics.',
    ['Marketing', 'OG Image'],
    'vercel-social-cards',
    [
      n('app_1', 'app', 'Web', 60, 180),
      n('ogImage_2', 'ogImage', 'OgImage', 360, 80),
      n('blob_3', 'blob', 'Media', 360, 220),
      n('analytics_4', 'analytics', 'Analytics', 60, 60),
      n('speedInsights_5', 'speedInsights', 'SpeedInsights', 60, 320),
    ],
    [e('e1', 'app_1', 'blob_3', 'storesFileIn')],
  ),
  vercel(
    'vercel-durable-commerce',
    'Durable Commerce Backbone',
    'Stripe webhook kicks off a durable Vercel Workflow that charges, waits, and ships — with an order queue, Postgres, and Resend receipts. Survives deploys and crashes.',
    ['Commerce', 'Flagship', 'Durable'],
    'vercel-commerce',
    [
      n('app_1', 'app', 'Web', 60, 220),
      n('webhook_2', 'webhook', 'StripeHook', 60, 60),
      n('workflow_3', 'workflow', 'Fulfillment', 360, 120),
      n('queue_4', 'queue', 'Orders', 360, 260),
      n('consumer_5', 'consumer', 'ProcessOrder', 640, 260),
      n('postgres_6', 'postgres', 'OrderDb', 360, 380),
      n('email_7', 'email', 'Receipts', 60, 380),
    ],
    [
      e('e1', 'app_1', 'workflow_3', 'triggersWorkflow'),
      e('e2', 'app_1', 'queue_4', 'enqueuesTo'),
      e('e3', 'queue_4', 'consumer_5', 'consumedBy'),
      e('e4', 'app_1', 'postgres_6', 'writesToService'),
      e('e5', 'app_1', 'email_7', 'sendsEmailThrough'),
    ],
  ),
  vercel(
    'vercel-progressive-rollout',
    'Progressive Rollout Platform',
    'Feature flags backed by Edge Config (flip flags with no redeploy), the Flags Explorer endpoint, Postgres data, and background tracking via after().',
    ['Flags', 'Platform'],
    'vercel-rollout',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('featureFlags_2', 'featureFlags', 'Flags', 360, 80),
      n('edgeConfig_3', 'edgeConfig', 'Config', 640, 80),
      n('postgres_4', 'postgres', 'Db', 360, 240),
      n('afterResponse_5', 'afterResponse', 'Background', 60, 60),
    ],
    [
      e('e1', 'app_1', 'featureFlags_2', 'readsFlags'),
      e('e2', 'featureFlags_2', 'edgeConfig_3', 'flagsBackedBy'),
      e('e3', 'app_1', 'postgres_4', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-hardened-api',
    'Hardened Public API',
    'An abuse-resistant JSON API: WAF rate-limiting (checkRateLimit), Postgres storage, Upstash Redis, and a partner webhook.',
    ['API', 'Security'],
    'vercel-hardened-api',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('rateLimit_2', 'rateLimit', 'RateLimit', 360, 80),
      n('postgres_3', 'postgres', 'Db', 360, 220),
      n('redis_4', 'redis', 'Cache', 360, 340),
      n('webhook_5', 'webhook', 'PartnerHook', 60, 60, { provider: 'generic' }),
    ],
    [
      e('e1', 'app_1', 'postgres_3', 'writesToService'),
      e('e2', 'app_1', 'redis_4', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-doc-pipeline',
    'Document Processing Pipeline',
    'Upload to Blob, kick off a durable Workflow that extracts + summarizes via the AI Gateway, queue the heavy steps, and store results in Postgres.',
    ['AI', 'Pipeline', 'Durable'],
    'vercel-doc-pipeline',
    [
      n('app_1', 'app', 'Web', 60, 220),
      n('blob_2', 'blob', 'Uploads', 360, 60),
      n('workflow_3', 'workflow', 'Ingest', 360, 180),
      n('aiGateway_4', 'aiGateway', 'Chat', 360, 300),
      n('queue_5', 'queue', 'Heavy', 640, 180),
      n('consumer_6', 'consumer', 'Process', 880, 180),
      n('postgres_7', 'postgres', 'Results', 360, 420),
    ],
    [
      e('e1', 'app_1', 'blob_2', 'storesFileIn'),
      e('e2', 'app_1', 'workflow_3', 'triggersWorkflow'),
      e('e3', 'app_1', 'queue_5', 'enqueuesTo'),
      e('e4', 'queue_5', 'consumer_6', 'consumedBy'),
      e('e5', 'app_1', 'postgres_7', 'writesToService'),
    ],
  ),
  vercel(
    'vercel-geo-marketing',
    'Geo-Personalized Marketing Site',
    'Edge Middleware geo-routes visitors, Feature Flags (backed by Edge Config) drive a progressive rollout, dynamic OG images, and full Web Analytics + Speed Insights.',
    ['Marketing', 'Flagship', 'Edge'],
    'vercel-geo',
    [
      n('app_1', 'app', 'Web', 60, 220),
      n('edgeMiddleware_2', 'edgeMiddleware', 'Proxy', 60, 60),
      n('edgeConfig_3', 'edgeConfig', 'Config', 640, 120),
      n('featureFlags_4', 'featureFlags', 'Flags', 360, 120),
      n('ogImage_5', 'ogImage', 'OgImage', 360, 280),
      n('analytics_6', 'analytics', 'Analytics', 360, 400),
      n('speedInsights_7', 'speedInsights', 'SpeedInsights', 640, 400),
    ],
    [
      e('e1', 'app_1', 'featureFlags_4', 'readsFlags'),
      e('e2', 'featureFlags_4', 'edgeConfig_3', 'flagsBackedBy'),
      e('e3', 'app_1', 'edgeConfig_3', 'readsConfig'),
    ],
  ),
  vercel(
    'vercel-hardened-ai',
    'Hardened AI Assistant',
    'A streaming AI Gateway chat protected by BotID and WAF rate-limiting, with history in Postgres — abuse-resistant by construction.',
    ['AI', 'Security', 'Flagship'],
    'vercel-hardened-ai',
    [
      n('app_1', 'app', 'Web', 60, 200),
      n('aiGateway_2', 'aiGateway', 'Chat', 360, 80, { model: 'openai/gpt-4o' }),
      n('botId_3', 'botId', 'BotId', 60, 60),
      n('rateLimit_4', 'rateLimit', 'RateLimit', 360, 320),
      n('postgres_5', 'postgres', 'History', 640, 200),
    ],
    [e('e1', 'app_1', 'postgres_5', 'writesToService')],
  ),
];
